// Code generated by Kitex v0.16.1. DO NOT EDIT.

package marketingservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	marketing "hxzCar-admin/kitex_gen/hxzcar/marketing"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListActivity": kitex.NewMethodInfo(
		listActivityHandler,
		newMarketingServiceListActivityArgs,
		newMarketingServiceListActivityResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetActivity": kitex.NewMethodInfo(
		getActivityHandler,
		newMarketingServiceGetActivityArgs,
		newMarketingServiceGetActivityResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListCoupon": kitex.NewMethodInfo(
		listCouponHandler,
		newMarketingServiceListCouponArgs,
		newMarketingServiceListCouponResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IssueCoupon": kitex.NewMethodInfo(
		issueCouponHandler,
		newMarketingServiceIssueCouponArgs,
		newMarketingServiceIssueCouponResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	marketingServiceServiceInfo                = NewServiceInfo()
	marketingServiceServiceInfoForClient       = NewServiceInfoForClient()
	marketingServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return marketingServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return marketingServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return marketingServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MarketingService"
	handlerType := (*marketing.MarketingService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "marketing",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func listActivityHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*marketing.MarketingServiceListActivityArgs)
	realResult := result.(*marketing.MarketingServiceListActivityResult)
	success, err := handler.(marketing.MarketingService).ListActivity(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMarketingServiceListActivityArgs() interface{} {
	return marketing.NewMarketingServiceListActivityArgs()
}

func newMarketingServiceListActivityResult() interface{} {
	return marketing.NewMarketingServiceListActivityResult()
}

func getActivityHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*marketing.MarketingServiceGetActivityArgs)
	realResult := result.(*marketing.MarketingServiceGetActivityResult)
	success, err := handler.(marketing.MarketingService).GetActivity(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMarketingServiceGetActivityArgs() interface{} {
	return marketing.NewMarketingServiceGetActivityArgs()
}

func newMarketingServiceGetActivityResult() interface{} {
	return marketing.NewMarketingServiceGetActivityResult()
}

func listCouponHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*marketing.MarketingServiceListCouponArgs)
	realResult := result.(*marketing.MarketingServiceListCouponResult)
	success, err := handler.(marketing.MarketingService).ListCoupon(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMarketingServiceListCouponArgs() interface{} {
	return marketing.NewMarketingServiceListCouponArgs()
}

func newMarketingServiceListCouponResult() interface{} {
	return marketing.NewMarketingServiceListCouponResult()
}

func issueCouponHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*marketing.MarketingServiceIssueCouponArgs)
	realResult := result.(*marketing.MarketingServiceIssueCouponResult)
	success, err := handler.(marketing.MarketingService).IssueCoupon(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMarketingServiceIssueCouponArgs() interface{} {
	return marketing.NewMarketingServiceIssueCouponArgs()
}

func newMarketingServiceIssueCouponResult() interface{} {
	return marketing.NewMarketingServiceIssueCouponResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListActivity(ctx context.Context, req *marketing.ListActivityReq) (r *marketing.ListActivityResp, err error) {
	var _args marketing.MarketingServiceListActivityArgs
	_args.Req = req
	var _result marketing.MarketingServiceListActivityResult
	if err = p.c.Call(ctx, "ListActivity", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetActivity(ctx context.Context, req *marketing.GetActivityReq) (r *marketing.GetActivityResp, err error) {
	var _args marketing.MarketingServiceGetActivityArgs
	_args.Req = req
	var _result marketing.MarketingServiceGetActivityResult
	if err = p.c.Call(ctx, "GetActivity", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListCoupon(ctx context.Context, req *marketing.ListCouponReq) (r *marketing.ListCouponResp, err error) {
	var _args marketing.MarketingServiceListCouponArgs
	_args.Req = req
	var _result marketing.MarketingServiceListCouponResult
	if err = p.c.Call(ctx, "ListCoupon", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IssueCoupon(ctx context.Context, req *marketing.IssueCouponReq) (r *marketing.IssueCouponResp, err error) {
	var _args marketing.MarketingServiceIssueCouponArgs
	_args.Req = req
	var _result marketing.MarketingServiceIssueCouponResult
	if err = p.c.Call(ctx, "IssueCoupon", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
