// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package pricing

import (
	"context"
	"fmt"
	"hxzCar-admin/kitex_gen/hxzcar/base"
)

type PricingRule struct {
	Id           int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	RuleName     string  `thrift:"rule_name,2" frugal:"2,default,string" json:"rule_name"`
	CityId       int64   `thrift:"city_id,3" frugal:"3,default,i64" json:"city_id"`
	CityName     string  `thrift:"city_name,4" frugal:"4,default,string" json:"city_name"`
	VehicleType  string  `thrift:"vehicle_type,5" frugal:"5,default,string" json:"vehicle_type"`
	StartTime    string  `thrift:"start_time,6" frugal:"6,default,string" json:"start_time"`
	EndTime      string  `thrift:"end_time,7" frugal:"7,default,string" json:"end_time"`
	BaseFare     float64 `thrift:"base_fare,8" frugal:"8,default,double" json:"base_fare"`
	BaseDistance float64 `thrift:"base_distance,9" frugal:"9,default,double" json:"base_distance"`
	DistanceFare float64 `thrift:"distance_fare,10" frugal:"10,default,double" json:"distance_fare"`
	TimeFare     float64 `thrift:"time_fare,11" frugal:"11,default,double" json:"time_fare"`
	MinFare      float64 `thrift:"min_fare,12" frugal:"12,default,double" json:"min_fare"`
	Status       int32   `thrift:"status,13" frugal:"13,default,i32" json:"status"`
	CreateTime   string  `thrift:"create_time,14" frugal:"14,default,string" json:"create_time"`
	UpdateTime   string  `thrift:"update_time,15" frugal:"15,default,string" json:"update_time"`
}

func NewPricingRule() *PricingRule {
	return &PricingRule{}
}

func (p *PricingRule) InitDefault() {
}

func (p *PricingRule) GetId() (v int64) {
	return p.Id
}

func (p *PricingRule) GetRuleName() (v string) {
	return p.RuleName
}

func (p *PricingRule) GetCityId() (v int64) {
	return p.CityId
}

func (p *PricingRule) GetCityName() (v string) {
	return p.CityName
}

func (p *PricingRule) GetVehicleType() (v string) {
	return p.VehicleType
}

func (p *PricingRule) GetStartTime() (v string) {
	return p.StartTime
}

func (p *PricingRule) GetEndTime() (v string) {
	return p.EndTime
}

func (p *PricingRule) GetBaseFare() (v float64) {
	return p.BaseFare
}

func (p *PricingRule) GetBaseDistance() (v float64) {
	return p.BaseDistance
}

func (p *PricingRule) GetDistanceFare() (v float64) {
	return p.DistanceFare
}

func (p *PricingRule) GetTimeFare() (v float64) {
	return p.TimeFare
}

func (p *PricingRule) GetMinFare() (v float64) {
	return p.MinFare
}

func (p *PricingRule) GetStatus() (v int32) {
	return p.Status
}

func (p *PricingRule) GetCreateTime() (v string) {
	return p.CreateTime
}

func (p *PricingRule) GetUpdateTime() (v string) {
	return p.UpdateTime
}
func (p *PricingRule) SetId(val int64) {
	p.Id = val
}
func (p *PricingRule) SetRuleName(val string) {
	p.RuleName = val
}
func (p *PricingRule) SetCityId(val int64) {
	p.CityId = val
}
func (p *PricingRule) SetCityName(val string) {
	p.CityName = val
}
func (p *PricingRule) SetVehicleType(val string) {
	p.VehicleType = val
}
func (p *PricingRule) SetStartTime(val string) {
	p.StartTime = val
}
func (p *PricingRule) SetEndTime(val string) {
	p.EndTime = val
}
func (p *PricingRule) SetBaseFare(val float64) {
	p.BaseFare = val
}
func (p *PricingRule) SetBaseDistance(val float64) {
	p.BaseDistance = val
}
func (p *PricingRule) SetDistanceFare(val float64) {
	p.DistanceFare = val
}
func (p *PricingRule) SetTimeFare(val float64) {
	p.TimeFare = val
}
func (p *PricingRule) SetMinFare(val float64) {
	p.MinFare = val
}
func (p *PricingRule) SetStatus(val int32) {
	p.Status = val
}
func (p *PricingRule) SetCreateTime(val string) {
	p.CreateTime = val
}
func (p *PricingRule) SetUpdateTime(val string) {
	p.UpdateTime = val
}

func (p *PricingRule) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingRule(%+v)", *p)
}

var fieldIDToName_PricingRule = map[int16]string{
	1:  "id",
	2:  "rule_name",
	3:  "city_id",
	4:  "city_name",
	5:  "vehicle_type",
	6:  "start_time",
	7:  "end_time",
	8:  "base_fare",
	9:  "base_distance",
	10: "distance_fare",
	11: "time_fare",
	12: "min_fare",
	13: "status",
	14: "create_time",
	15: "update_time",
}

type ListRuleReq struct {
	CityId      int64  `thrift:"city_id,1" frugal:"1,default,i64" json:"city_id"`
	VehicleType string `thrift:"vehicle_type,2" frugal:"2,default,string" json:"vehicle_type"`
	Status      int32  `thrift:"status,3" frugal:"3,default,i32" json:"status"`
	Page        int32  `thrift:"page,4" frugal:"4,default,i32" json:"page"`
	PageSize    int32  `thrift:"page_size,5" frugal:"5,default,i32" json:"page_size"`
}

func NewListRuleReq() *ListRuleReq {
	return &ListRuleReq{}
}

func (p *ListRuleReq) InitDefault() {
}

func (p *ListRuleReq) GetCityId() (v int64) {
	return p.CityId
}

func (p *ListRuleReq) GetVehicleType() (v string) {
	return p.VehicleType
}

func (p *ListRuleReq) GetStatus() (v int32) {
	return p.Status
}

func (p *ListRuleReq) GetPage() (v int32) {
	return p.Page
}

func (p *ListRuleReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *ListRuleReq) SetCityId(val int64) {
	p.CityId = val
}
func (p *ListRuleReq) SetVehicleType(val string) {
	p.VehicleType = val
}
func (p *ListRuleReq) SetStatus(val int32) {
	p.Status = val
}
func (p *ListRuleReq) SetPage(val int32) {
	p.Page = val
}
func (p *ListRuleReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *ListRuleReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListRuleReq(%+v)", *p)
}

var fieldIDToName_ListRuleReq = map[int16]string{
	1: "city_id",
	2: "vehicle_type",
	3: "status",
	4: "page",
	5: "page_size",
}

type ListRuleResp struct {
	Rules    []*PricingRule `thrift:"rules,1" frugal:"1,default,list<PricingRule>" json:"rules"`
	Total    int64          `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewListRuleResp() *ListRuleResp {
	return &ListRuleResp{}
}

func (p *ListRuleResp) InitDefault() {
}

func (p *ListRuleResp) GetRules() (v []*PricingRule) {
	return p.Rules
}

func (p *ListRuleResp) GetTotal() (v int64) {
	return p.Total
}

var ListRuleResp_BaseResp_DEFAULT *base.BaseResp

func (p *ListRuleResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListRuleResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListRuleResp) SetRules(val []*PricingRule) {
	p.Rules = val
}
func (p *ListRuleResp) SetTotal(val int64) {
	p.Total = val
}
func (p *ListRuleResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListRuleResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListRuleResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListRuleResp(%+v)", *p)
}

var fieldIDToName_ListRuleResp = map[int16]string{
	1:   "rules",
	2:   "total",
	255: "baseResp",
}

type GetRuleReq struct {
	RuleId int64 `thrift:"rule_id,1" frugal:"1,default,i64" json:"rule_id"`
}

func NewGetRuleReq() *GetRuleReq {
	return &GetRuleReq{}
}

func (p *GetRuleReq) InitDefault() {
}

func (p *GetRuleReq) GetRuleId() (v int64) {
	return p.RuleId
}
func (p *GetRuleReq) SetRuleId(val int64) {
	p.RuleId = val
}

func (p *GetRuleReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRuleReq(%+v)", *p)
}

var fieldIDToName_GetRuleReq = map[int16]string{
	1: "rule_id",
}

type GetRuleResp struct {
	Rule     *PricingRule   `thrift:"rule,1" frugal:"1,default,PricingRule" json:"rule"`
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewGetRuleResp() *GetRuleResp {
	return &GetRuleResp{}
}

func (p *GetRuleResp) InitDefault() {
}

var GetRuleResp_Rule_DEFAULT *PricingRule

func (p *GetRuleResp) GetRule() (v *PricingRule) {
	if !p.IsSetRule() {
		return GetRuleResp_Rule_DEFAULT
	}
	return p.Rule
}

var GetRuleResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetRuleResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetRuleResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetRuleResp) SetRule(val *PricingRule) {
	p.Rule = val
}
func (p *GetRuleResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetRuleResp) IsSetRule() bool {
	return p.Rule != nil
}

func (p *GetRuleResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetRuleResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRuleResp(%+v)", *p)
}

var fieldIDToName_GetRuleResp = map[int16]string{
	1:   "rule",
	255: "baseResp",
}

type CreateRuleReq struct {
	RuleName     string  `thrift:"rule_name,1" frugal:"1,default,string" json:"rule_name"`
	CityId       int64   `thrift:"city_id,2" frugal:"2,default,i64" json:"city_id"`
	CityName     string  `thrift:"city_name,3" frugal:"3,default,string" json:"city_name"`
	VehicleType  string  `thrift:"vehicle_type,4" frugal:"4,default,string" json:"vehicle_type"`
	StartTime    string  `thrift:"start_time,5" frugal:"5,default,string" json:"start_time"`
	EndTime      string  `thrift:"end_time,6" frugal:"6,default,string" json:"end_time"`
	BaseFare     float64 `thrift:"base_fare,7" frugal:"7,default,double" json:"base_fare"`
	BaseDistance float64 `thrift:"base_distance,8" frugal:"8,default,double" json:"base_distance"`
	DistanceFare float64 `thrift:"distance_fare,9" frugal:"9,default,double" json:"distance_fare"`
	TimeFare     float64 `thrift:"time_fare,10" frugal:"10,default,double" json:"time_fare"`
	MinFare      float64 `thrift:"min_fare,11" frugal:"11,default,double" json:"min_fare"`
	Status       int32   `thrift:"status,12" frugal:"12,default,i32" json:"status"`
}

func NewCreateRuleReq() *CreateRuleReq {
	return &CreateRuleReq{}
}

func (p *CreateRuleReq) InitDefault() {
}

func (p *CreateRuleReq) GetRuleName() (v string) {
	return p.RuleName
}

func (p *CreateRuleReq) GetCityId() (v int64) {
	return p.CityId
}

func (p *CreateRuleReq) GetCityName() (v string) {
	return p.CityName
}

func (p *CreateRuleReq) GetVehicleType() (v string) {
	return p.VehicleType
}

func (p *CreateRuleReq) GetStartTime() (v string) {
	return p.StartTime
}

func (p *CreateRuleReq) GetEndTime() (v string) {
	return p.EndTime
}

func (p *CreateRuleReq) GetBaseFare() (v float64) {
	return p.BaseFare
}

func (p *CreateRuleReq) GetBaseDistance() (v float64) {
	return p.BaseDistance
}

func (p *CreateRuleReq) GetDistanceFare() (v float64) {
	return p.DistanceFare
}

func (p *CreateRuleReq) GetTimeFare() (v float64) {
	return p.TimeFare
}

func (p *CreateRuleReq) GetMinFare() (v float64) {
	return p.MinFare
}

func (p *CreateRuleReq) GetStatus() (v int32) {
	return p.Status
}
func (p *CreateRuleReq) SetRuleName(val string) {
	p.RuleName = val
}
func (p *CreateRuleReq) SetCityId(val int64) {
	p.CityId = val
}
func (p *CreateRuleReq) SetCityName(val string) {
	p.CityName = val
}
func (p *CreateRuleReq) SetVehicleType(val string) {
	p.VehicleType = val
}
func (p *CreateRuleReq) SetStartTime(val string) {
	p.StartTime = val
}
func (p *CreateRuleReq) SetEndTime(val string) {
	p.EndTime = val
}
func (p *CreateRuleReq) SetBaseFare(val float64) {
	p.BaseFare = val
}
func (p *CreateRuleReq) SetBaseDistance(val float64) {
	p.BaseDistance = val
}
func (p *CreateRuleReq) SetDistanceFare(val float64) {
	p.DistanceFare = val
}
func (p *CreateRuleReq) SetTimeFare(val float64) {
	p.TimeFare = val
}
func (p *CreateRuleReq) SetMinFare(val float64) {
	p.MinFare = val
}
func (p *CreateRuleReq) SetStatus(val int32) {
	p.Status = val
}

func (p *CreateRuleReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateRuleReq(%+v)", *p)
}

var fieldIDToName_CreateRuleReq = map[int16]string{
	1:  "rule_name",
	2:  "city_id",
	3:  "city_name",
	4:  "vehicle_type",
	5:  "start_time",
	6:  "end_time",
	7:  "base_fare",
	8:  "base_distance",
	9:  "distance_fare",
	10: "time_fare",
	11: "min_fare",
	12: "status",
}

type CreateRuleResp struct {
	RuleId   int64          `thrift:"rule_id,1" frugal:"1,default,i64" json:"rule_id"`
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewCreateRuleResp() *CreateRuleResp {
	return &CreateRuleResp{}
}

func (p *CreateRuleResp) InitDefault() {
}

func (p *CreateRuleResp) GetRuleId() (v int64) {
	return p.RuleId
}

var CreateRuleResp_BaseResp_DEFAULT *base.BaseResp

func (p *CreateRuleResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateRuleResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CreateRuleResp) SetRuleId(val int64) {
	p.RuleId = val
}
func (p *CreateRuleResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CreateRuleResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateRuleResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateRuleResp(%+v)", *p)
}

var fieldIDToName_CreateRuleResp = map[int16]string{
	1:   "rule_id",
	255: "baseResp",
}

type UpdateRuleReq struct {
	RuleId       int64   `thrift:"rule_id,1" frugal:"1,default,i64" json:"rule_id"`
	RuleName     string  `thrift:"rule_name,2" frugal:"2,default,string" json:"rule_name"`
	CityId       int64   `thrift:"city_id,3" frugal:"3,default,i64" json:"city_id"`
	CityName     string  `thrift:"city_name,4" frugal:"4,default,string" json:"city_name"`
	VehicleType  string  `thrift:"vehicle_type,5" frugal:"5,default,string" json:"vehicle_type"`
	StartTime    string  `thrift:"start_time,6" frugal:"6,default,string" json:"start_time"`
	EndTime      string  `thrift:"end_time,7" frugal:"7,default,string" json:"end_time"`
	BaseFare     float64 `thrift:"base_fare,8" frugal:"8,default,double" json:"base_fare"`
	BaseDistance float64 `thrift:"base_distance,9" frugal:"9,default,double" json:"base_distance"`
	DistanceFare float64 `thrift:"distance_fare,10" frugal:"10,default,double" json:"distance_fare"`
	TimeFare     float64 `thrift:"time_fare,11" frugal:"11,default,double" json:"time_fare"`
	MinFare      float64 `thrift:"min_fare,12" frugal:"12,default,double" json:"min_fare"`
	Status       int32   `thrift:"status,13" frugal:"13,default,i32" json:"status"`
}

func NewUpdateRuleReq() *UpdateRuleReq {
	return &UpdateRuleReq{}
}

func (p *UpdateRuleReq) InitDefault() {
}

func (p *UpdateRuleReq) GetRuleId() (v int64) {
	return p.RuleId
}

func (p *UpdateRuleReq) GetRuleName() (v string) {
	return p.RuleName
}

func (p *UpdateRuleReq) GetCityId() (v int64) {
	return p.CityId
}

func (p *UpdateRuleReq) GetCityName() (v string) {
	return p.CityName
}

func (p *UpdateRuleReq) GetVehicleType() (v string) {
	return p.VehicleType
}

func (p *UpdateRuleReq) GetStartTime() (v string) {
	return p.StartTime
}

func (p *UpdateRuleReq) GetEndTime() (v string) {
	return p.EndTime
}

func (p *UpdateRuleReq) GetBaseFare() (v float64) {
	return p.BaseFare
}

func (p *UpdateRuleReq) GetBaseDistance() (v float64) {
	return p.BaseDistance
}

func (p *UpdateRuleReq) GetDistanceFare() (v float64) {
	return p.DistanceFare
}

func (p *UpdateRuleReq) GetTimeFare() (v float64) {
	return p.TimeFare
}

func (p *UpdateRuleReq) GetMinFare() (v float64) {
	return p.MinFare
}

func (p *UpdateRuleReq) GetStatus() (v int32) {
	return p.Status
}
func (p *UpdateRuleReq) SetRuleId(val int64) {
	p.RuleId = val
}
func (p *UpdateRuleReq) SetRuleName(val string) {
	p.RuleName = val
}
func (p *UpdateRuleReq) SetCityId(val int64) {
	p.CityId = val
}
func (p *UpdateRuleReq) SetCityName(val string) {
	p.CityName = val
}
func (p *UpdateRuleReq) SetVehicleType(val string) {
	p.VehicleType = val
}
func (p *UpdateRuleReq) SetStartTime(val string) {
	p.StartTime = val
}
func (p *UpdateRuleReq) SetEndTime(val string) {
	p.EndTime = val
}
func (p *UpdateRuleReq) SetBaseFare(val float64) {
	p.BaseFare = val
}
func (p *UpdateRuleReq) SetBaseDistance(val float64) {
	p.BaseDistance = val
}
func (p *UpdateRuleReq) SetDistanceFare(val float64) {
	p.DistanceFare = val
}
func (p *UpdateRuleReq) SetTimeFare(val float64) {
	p.TimeFare = val
}
func (p *UpdateRuleReq) SetMinFare(val float64) {
	p.MinFare = val
}
func (p *UpdateRuleReq) SetStatus(val int32) {
	p.Status = val
}

func (p *UpdateRuleReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateRuleReq(%+v)", *p)
}

var fieldIDToName_UpdateRuleReq = map[int16]string{
	1:  "rule_id",
	2:  "rule_name",
	3:  "city_id",
	4:  "city_name",
	5:  "vehicle_type",
	6:  "start_time",
	7:  "end_time",
	8:  "base_fare",
	9:  "base_distance",
	10: "distance_fare",
	11: "time_fare",
	12: "min_fare",
	13: "status",
}

type UpdateRuleResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewUpdateRuleResp() *UpdateRuleResp {
	return &UpdateRuleResp{}
}

func (p *UpdateRuleResp) InitDefault() {
}

var UpdateRuleResp_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateRuleResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateRuleResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateRuleResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateRuleResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateRuleResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateRuleResp(%+v)", *p)
}

var fieldIDToName_UpdateRuleResp = map[int16]string{
	255: "baseResp",
}

type DeleteRuleReq struct {
	RuleId int64 `thrift:"rule_id,1" frugal:"1,default,i64" json:"rule_id"`
}

func NewDeleteRuleReq() *DeleteRuleReq {
	return &DeleteRuleReq{}
}

func (p *DeleteRuleReq) InitDefault() {
}

func (p *DeleteRuleReq) GetRuleId() (v int64) {
	return p.RuleId
}
func (p *DeleteRuleReq) SetRuleId(val int64) {
	p.RuleId = val
}

func (p *DeleteRuleReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteRuleReq(%+v)", *p)
}

var fieldIDToName_DeleteRuleReq = map[int16]string{
	1: "rule_id",
}

type DeleteRuleResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewDeleteRuleResp() *DeleteRuleResp {
	return &DeleteRuleResp{}
}

func (p *DeleteRuleResp) InitDefault() {
}

var DeleteRuleResp_BaseResp_DEFAULT *base.BaseResp

func (p *DeleteRuleResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DeleteRuleResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteRuleResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DeleteRuleResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteRuleResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteRuleResp(%+v)", *p)
}

var fieldIDToName_DeleteRuleResp = map[int16]string{
	255: "baseResp",
}

type PricingService interface {
	ListRule(ctx context.Context, req *ListRuleReq) (r *ListRuleResp, err error)

	GetRule(ctx context.Context, req *GetRuleReq) (r *GetRuleResp, err error)

	CreateRule(ctx context.Context, req *CreateRuleReq) (r *CreateRuleResp, err error)

	UpdateRule(ctx context.Context, req *UpdateRuleReq) (r *UpdateRuleResp, err error)

	DeleteRule(ctx context.Context, req *DeleteRuleReq) (r *DeleteRuleResp, err error)
}

type PricingServiceListRuleArgs struct {
	Req *ListRuleReq `thrift:"req,1" frugal:"1,default,ListRuleReq" json:"req"`
}

func NewPricingServiceListRuleArgs() *PricingServiceListRuleArgs {
	return &PricingServiceListRuleArgs{}
}

func (p *PricingServiceListRuleArgs) InitDefault() {
}

var PricingServiceListRuleArgs_Req_DEFAULT *ListRuleReq

func (p *PricingServiceListRuleArgs) GetReq() (v *ListRuleReq) {
	if !p.IsSetReq() {
		return PricingServiceListRuleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PricingServiceListRuleArgs) SetReq(val *ListRuleReq) {
	p.Req = val
}

func (p *PricingServiceListRuleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PricingServiceListRuleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingServiceListRuleArgs(%+v)", *p)
}

var fieldIDToName_PricingServiceListRuleArgs = map[int16]string{
	1: "req",
}

type PricingServiceListRuleResult struct {
	Success *ListRuleResp `thrift:"success,0,optional" frugal:"0,optional,ListRuleResp" json:"success,omitempty"`
}

func NewPricingServiceListRuleResult() *PricingServiceListRuleResult {
	return &PricingServiceListRuleResult{}
}

func (p *PricingServiceListRuleResult) InitDefault() {
}

var PricingServiceListRuleResult_Success_DEFAULT *ListRuleResp

func (p *PricingServiceListRuleResult) GetSuccess() (v *ListRuleResp) {
	if !p.IsSetSuccess() {
		return PricingServiceListRuleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PricingServiceListRuleResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListRuleResp)
}

func (p *PricingServiceListRuleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PricingServiceListRuleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingServiceListRuleResult(%+v)", *p)
}

var fieldIDToName_PricingServiceListRuleResult = map[int16]string{
	0: "success",
}

type PricingServiceGetRuleArgs struct {
	Req *GetRuleReq `thrift:"req,1" frugal:"1,default,GetRuleReq" json:"req"`
}

func NewPricingServiceGetRuleArgs() *PricingServiceGetRuleArgs {
	return &PricingServiceGetRuleArgs{}
}

func (p *PricingServiceGetRuleArgs) InitDefault() {
}

var PricingServiceGetRuleArgs_Req_DEFAULT *GetRuleReq

func (p *PricingServiceGetRuleArgs) GetReq() (v *GetRuleReq) {
	if !p.IsSetReq() {
		return PricingServiceGetRuleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PricingServiceGetRuleArgs) SetReq(val *GetRuleReq) {
	p.Req = val
}

func (p *PricingServiceGetRuleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PricingServiceGetRuleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingServiceGetRuleArgs(%+v)", *p)
}

var fieldIDToName_PricingServiceGetRuleArgs = map[int16]string{
	1: "req",
}

type PricingServiceGetRuleResult struct {
	Success *GetRuleResp `thrift:"success,0,optional" frugal:"0,optional,GetRuleResp" json:"success,omitempty"`
}

func NewPricingServiceGetRuleResult() *PricingServiceGetRuleResult {
	return &PricingServiceGetRuleResult{}
}

func (p *PricingServiceGetRuleResult) InitDefault() {
}

var PricingServiceGetRuleResult_Success_DEFAULT *GetRuleResp

func (p *PricingServiceGetRuleResult) GetSuccess() (v *GetRuleResp) {
	if !p.IsSetSuccess() {
		return PricingServiceGetRuleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PricingServiceGetRuleResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetRuleResp)
}

func (p *PricingServiceGetRuleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PricingServiceGetRuleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingServiceGetRuleResult(%+v)", *p)
}

var fieldIDToName_PricingServiceGetRuleResult = map[int16]string{
	0: "success",
}

type PricingServiceCreateRuleArgs struct {
	Req *CreateRuleReq `thrift:"req,1" frugal:"1,default,CreateRuleReq" json:"req"`
}

func NewPricingServiceCreateRuleArgs() *PricingServiceCreateRuleArgs {
	return &PricingServiceCreateRuleArgs{}
}

func (p *PricingServiceCreateRuleArgs) InitDefault() {
}

var PricingServiceCreateRuleArgs_Req_DEFAULT *CreateRuleReq

func (p *PricingServiceCreateRuleArgs) GetReq() (v *CreateRuleReq) {
	if !p.IsSetReq() {
		return PricingServiceCreateRuleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PricingServiceCreateRuleArgs) SetReq(val *CreateRuleReq) {
	p.Req = val
}

func (p *PricingServiceCreateRuleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PricingServiceCreateRuleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingServiceCreateRuleArgs(%+v)", *p)
}

var fieldIDToName_PricingServiceCreateRuleArgs = map[int16]string{
	1: "req",
}

type PricingServiceCreateRuleResult struct {
	Success *CreateRuleResp `thrift:"success,0,optional" frugal:"0,optional,CreateRuleResp" json:"success,omitempty"`
}

func NewPricingServiceCreateRuleResult() *PricingServiceCreateRuleResult {
	return &PricingServiceCreateRuleResult{}
}

func (p *PricingServiceCreateRuleResult) InitDefault() {
}

var PricingServiceCreateRuleResult_Success_DEFAULT *CreateRuleResp

func (p *PricingServiceCreateRuleResult) GetSuccess() (v *CreateRuleResp) {
	if !p.IsSetSuccess() {
		return PricingServiceCreateRuleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PricingServiceCreateRuleResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateRuleResp)
}

func (p *PricingServiceCreateRuleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PricingServiceCreateRuleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingServiceCreateRuleResult(%+v)", *p)
}

var fieldIDToName_PricingServiceCreateRuleResult = map[int16]string{
	0: "success",
}

type PricingServiceUpdateRuleArgs struct {
	Req *UpdateRuleReq `thrift:"req,1" frugal:"1,default,UpdateRuleReq" json:"req"`
}

func NewPricingServiceUpdateRuleArgs() *PricingServiceUpdateRuleArgs {
	return &PricingServiceUpdateRuleArgs{}
}

func (p *PricingServiceUpdateRuleArgs) InitDefault() {
}

var PricingServiceUpdateRuleArgs_Req_DEFAULT *UpdateRuleReq

func (p *PricingServiceUpdateRuleArgs) GetReq() (v *UpdateRuleReq) {
	if !p.IsSetReq() {
		return PricingServiceUpdateRuleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PricingServiceUpdateRuleArgs) SetReq(val *UpdateRuleReq) {
	p.Req = val
}

func (p *PricingServiceUpdateRuleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PricingServiceUpdateRuleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingServiceUpdateRuleArgs(%+v)", *p)
}

var fieldIDToName_PricingServiceUpdateRuleArgs = map[int16]string{
	1: "req",
}

type PricingServiceUpdateRuleResult struct {
	Success *UpdateRuleResp `thrift:"success,0,optional" frugal:"0,optional,UpdateRuleResp" json:"success,omitempty"`
}

func NewPricingServiceUpdateRuleResult() *PricingServiceUpdateRuleResult {
	return &PricingServiceUpdateRuleResult{}
}

func (p *PricingServiceUpdateRuleResult) InitDefault() {
}

var PricingServiceUpdateRuleResult_Success_DEFAULT *UpdateRuleResp

func (p *PricingServiceUpdateRuleResult) GetSuccess() (v *UpdateRuleResp) {
	if !p.IsSetSuccess() {
		return PricingServiceUpdateRuleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PricingServiceUpdateRuleResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateRuleResp)
}

func (p *PricingServiceUpdateRuleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PricingServiceUpdateRuleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingServiceUpdateRuleResult(%+v)", *p)
}

var fieldIDToName_PricingServiceUpdateRuleResult = map[int16]string{
	0: "success",
}

type PricingServiceDeleteRuleArgs struct {
	Req *DeleteRuleReq `thrift:"req,1" frugal:"1,default,DeleteRuleReq" json:"req"`
}

func NewPricingServiceDeleteRuleArgs() *PricingServiceDeleteRuleArgs {
	return &PricingServiceDeleteRuleArgs{}
}

func (p *PricingServiceDeleteRuleArgs) InitDefault() {
}

var PricingServiceDeleteRuleArgs_Req_DEFAULT *DeleteRuleReq

func (p *PricingServiceDeleteRuleArgs) GetReq() (v *DeleteRuleReq) {
	if !p.IsSetReq() {
		return PricingServiceDeleteRuleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PricingServiceDeleteRuleArgs) SetReq(val *DeleteRuleReq) {
	p.Req = val
}

func (p *PricingServiceDeleteRuleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PricingServiceDeleteRuleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingServiceDeleteRuleArgs(%+v)", *p)
}

var fieldIDToName_PricingServiceDeleteRuleArgs = map[int16]string{
	1: "req",
}

type PricingServiceDeleteRuleResult struct {
	Success *DeleteRuleResp `thrift:"success,0,optional" frugal:"0,optional,DeleteRuleResp" json:"success,omitempty"`
}

func NewPricingServiceDeleteRuleResult() *PricingServiceDeleteRuleResult {
	return &PricingServiceDeleteRuleResult{}
}

func (p *PricingServiceDeleteRuleResult) InitDefault() {
}

var PricingServiceDeleteRuleResult_Success_DEFAULT *DeleteRuleResp

func (p *PricingServiceDeleteRuleResult) GetSuccess() (v *DeleteRuleResp) {
	if !p.IsSetSuccess() {
		return PricingServiceDeleteRuleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PricingServiceDeleteRuleResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteRuleResp)
}

func (p *PricingServiceDeleteRuleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PricingServiceDeleteRuleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingServiceDeleteRuleResult(%+v)", *p)
}

var fieldIDToName_PricingServiceDeleteRuleResult = map[int16]string{
	0: "success",
}
