// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package marketing

import (
	"context"
	"fmt"
	"hxzCar-admin/kitex_gen/hxzcar/base"
)

type MarketingActivity struct {
	Id               int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	ActivityName     string  `thrift:"activity_name,2" frugal:"2,default,string" json:"activity_name"`
	ActivityType     string  `thrift:"activity_type,3" frugal:"3,default,string" json:"activity_type"`
	BudgetTotal      float64 `thrift:"budget_total,4" frugal:"4,default,double" json:"budget_total"`
	BudgetUsed       float64 `thrift:"budget_used,5" frugal:"5,default,double" json:"budget_used"`
	ParticipantCount int32   `thrift:"participant_count,6" frugal:"6,default,i32" json:"participant_count"`
	StartTime        string  `thrift:"start_time,7" frugal:"7,default,string" json:"start_time"`
	EndTime          string  `thrift:"end_time,8" frugal:"8,default,string" json:"end_time"`
	Status           int32   `thrift:"status,9" frugal:"9,default,i32" json:"status"`
	CreateTime       string  `thrift:"create_time,10" frugal:"10,default,string" json:"create_time"`
	UpdateTime       string  `thrift:"update_time,11" frugal:"11,default,string" json:"update_time"`
}

func NewMarketingActivity() *MarketingActivity {
	return &MarketingActivity{}
}

func (p *MarketingActivity) InitDefault() {
}

func (p *MarketingActivity) GetId() (v int64) {
	return p.Id
}

func (p *MarketingActivity) GetActivityName() (v string) {
	return p.ActivityName
}

func (p *MarketingActivity) GetActivityType() (v string) {
	return p.ActivityType
}

func (p *MarketingActivity) GetBudgetTotal() (v float64) {
	return p.BudgetTotal
}

func (p *MarketingActivity) GetBudgetUsed() (v float64) {
	return p.BudgetUsed
}

func (p *MarketingActivity) GetParticipantCount() (v int32) {
	return p.ParticipantCount
}

func (p *MarketingActivity) GetStartTime() (v string) {
	return p.StartTime
}

func (p *MarketingActivity) GetEndTime() (v string) {
	return p.EndTime
}

func (p *MarketingActivity) GetStatus() (v int32) {
	return p.Status
}

func (p *MarketingActivity) GetCreateTime() (v string) {
	return p.CreateTime
}

func (p *MarketingActivity) GetUpdateTime() (v string) {
	return p.UpdateTime
}
func (p *MarketingActivity) SetId(val int64) {
	p.Id = val
}
func (p *MarketingActivity) SetActivityName(val string) {
	p.ActivityName = val
}
func (p *MarketingActivity) SetActivityType(val string) {
	p.ActivityType = val
}
func (p *MarketingActivity) SetBudgetTotal(val float64) {
	p.BudgetTotal = val
}
func (p *MarketingActivity) SetBudgetUsed(val float64) {
	p.BudgetUsed = val
}
func (p *MarketingActivity) SetParticipantCount(val int32) {
	p.ParticipantCount = val
}
func (p *MarketingActivity) SetStartTime(val string) {
	p.StartTime = val
}
func (p *MarketingActivity) SetEndTime(val string) {
	p.EndTime = val
}
func (p *MarketingActivity) SetStatus(val int32) {
	p.Status = val
}
func (p *MarketingActivity) SetCreateTime(val string) {
	p.CreateTime = val
}
func (p *MarketingActivity) SetUpdateTime(val string) {
	p.UpdateTime = val
}

func (p *MarketingActivity) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarketingActivity(%+v)", *p)
}

var fieldIDToName_MarketingActivity = map[int16]string{
	1:  "id",
	2:  "activity_name",
	3:  "activity_type",
	4:  "budget_total",
	5:  "budget_used",
	6:  "participant_count",
	7:  "start_time",
	8:  "end_time",
	9:  "status",
	10: "create_time",
	11: "update_time",
}

type Coupon struct {
	Id              int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	ActivityId      int64   `thrift:"activity_id,2" frugal:"2,default,i64" json:"activity_id"`
	CouponName      string  `thrift:"coupon_name,3" frugal:"3,default,string" json:"coupon_name"`
	CouponType      string  `thrift:"coupon_type,4" frugal:"4,default,string" json:"coupon_type"`
	Denomination    float64 `thrift:"denomination,5" frugal:"5,default,double" json:"denomination"`
	ConditionAmount float64 `thrift:"condition_amount,6" frugal:"6,default,double" json:"condition_amount"`
	TotalCount      int32   `thrift:"total_count,7" frugal:"7,default,i32" json:"total_count"`
	SendCount       int32   `thrift:"send_count,8" frugal:"8,default,i32" json:"send_count"`
	UsedCount       int32   `thrift:"used_count,9" frugal:"9,default,i32" json:"used_count"`
	ValidDays       int32   `thrift:"valid_days,10" frugal:"10,default,i32" json:"valid_days"`
	Status          int32   `thrift:"status,11" frugal:"11,default,i32" json:"status"`
	CreateTime      string  `thrift:"create_time,12" frugal:"12,default,string" json:"create_time"`
	UpdateTime      string  `thrift:"update_time,13" frugal:"13,default,string" json:"update_time"`
}

func NewCoupon() *Coupon {
	return &Coupon{}
}

func (p *Coupon) InitDefault() {
}

func (p *Coupon) GetId() (v int64) {
	return p.Id
}

func (p *Coupon) GetActivityId() (v int64) {
	return p.ActivityId
}

func (p *Coupon) GetCouponName() (v string) {
	return p.CouponName
}

func (p *Coupon) GetCouponType() (v string) {
	return p.CouponType
}

func (p *Coupon) GetDenomination() (v float64) {
	return p.Denomination
}

func (p *Coupon) GetConditionAmount() (v float64) {
	return p.ConditionAmount
}

func (p *Coupon) GetTotalCount() (v int32) {
	return p.TotalCount
}

func (p *Coupon) GetSendCount() (v int32) {
	return p.SendCount
}

func (p *Coupon) GetUsedCount() (v int32) {
	return p.UsedCount
}

func (p *Coupon) GetValidDays() (v int32) {
	return p.ValidDays
}

func (p *Coupon) GetStatus() (v int32) {
	return p.Status
}

func (p *Coupon) GetCreateTime() (v string) {
	return p.CreateTime
}

func (p *Coupon) GetUpdateTime() (v string) {
	return p.UpdateTime
}
func (p *Coupon) SetId(val int64) {
	p.Id = val
}
func (p *Coupon) SetActivityId(val int64) {
	p.ActivityId = val
}
func (p *Coupon) SetCouponName(val string) {
	p.CouponName = val
}
func (p *Coupon) SetCouponType(val string) {
	p.CouponType = val
}
func (p *Coupon) SetDenomination(val float64) {
	p.Denomination = val
}
func (p *Coupon) SetConditionAmount(val float64) {
	p.ConditionAmount = val
}
func (p *Coupon) SetTotalCount(val int32) {
	p.TotalCount = val
}
func (p *Coupon) SetSendCount(val int32) {
	p.SendCount = val
}
func (p *Coupon) SetUsedCount(val int32) {
	p.UsedCount = val
}
func (p *Coupon) SetValidDays(val int32) {
	p.ValidDays = val
}
func (p *Coupon) SetStatus(val int32) {
	p.Status = val
}
func (p *Coupon) SetCreateTime(val string) {
	p.CreateTime = val
}
func (p *Coupon) SetUpdateTime(val string) {
	p.UpdateTime = val
}

func (p *Coupon) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Coupon(%+v)", *p)
}

var fieldIDToName_Coupon = map[int16]string{
	1:  "id",
	2:  "activity_id",
	3:  "coupon_name",
	4:  "coupon_type",
	5:  "denomination",
	6:  "condition_amount",
	7:  "total_count",
	8:  "send_count",
	9:  "used_count",
	10: "valid_days",
	11: "status",
	12: "create_time",
	13: "update_time",
}

type ListActivityReq struct {
	Status       int32  `thrift:"status,1" frugal:"1,default,i32" json:"status"`
	ActivityType string `thrift:"activity_type,2" frugal:"2,default,string" json:"activity_type"`
	Page         int32  `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize     int32  `thrift:"page_size,4" frugal:"4,default,i32" json:"page_size"`
}

func NewListActivityReq() *ListActivityReq {
	return &ListActivityReq{}
}

func (p *ListActivityReq) InitDefault() {
}

func (p *ListActivityReq) GetStatus() (v int32) {
	return p.Status
}

func (p *ListActivityReq) GetActivityType() (v string) {
	return p.ActivityType
}

func (p *ListActivityReq) GetPage() (v int32) {
	return p.Page
}

func (p *ListActivityReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *ListActivityReq) SetStatus(val int32) {
	p.Status = val
}
func (p *ListActivityReq) SetActivityType(val string) {
	p.ActivityType = val
}
func (p *ListActivityReq) SetPage(val int32) {
	p.Page = val
}
func (p *ListActivityReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *ListActivityReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListActivityReq(%+v)", *p)
}

var fieldIDToName_ListActivityReq = map[int16]string{
	1: "status",
	2: "activity_type",
	3: "page",
	4: "page_size",
}

type ListActivityResp struct {
	Activities []*MarketingActivity `thrift:"activities,1" frugal:"1,default,list<MarketingActivity>" json:"activities"`
	Total      int64                `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	BaseResp   *base.BaseResp       `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewListActivityResp() *ListActivityResp {
	return &ListActivityResp{}
}

func (p *ListActivityResp) InitDefault() {
}

func (p *ListActivityResp) GetActivities() (v []*MarketingActivity) {
	return p.Activities
}

func (p *ListActivityResp) GetTotal() (v int64) {
	return p.Total
}

var ListActivityResp_BaseResp_DEFAULT *base.BaseResp

func (p *ListActivityResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListActivityResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListActivityResp) SetActivities(val []*MarketingActivity) {
	p.Activities = val
}
func (p *ListActivityResp) SetTotal(val int64) {
	p.Total = val
}
func (p *ListActivityResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListActivityResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListActivityResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListActivityResp(%+v)", *p)
}

var fieldIDToName_ListActivityResp = map[int16]string{
	1:   "activities",
	2:   "total",
	255: "baseResp",
}

type GetActivityReq struct {
	ActivityId int64 `thrift:"activity_id,1" frugal:"1,default,i64" json:"activity_id"`
}

func NewGetActivityReq() *GetActivityReq {
	return &GetActivityReq{}
}

func (p *GetActivityReq) InitDefault() {
}

func (p *GetActivityReq) GetActivityId() (v int64) {
	return p.ActivityId
}
func (p *GetActivityReq) SetActivityId(val int64) {
	p.ActivityId = val
}

func (p *GetActivityReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetActivityReq(%+v)", *p)
}

var fieldIDToName_GetActivityReq = map[int16]string{
	1: "activity_id",
}

type GetActivityResp struct {
	Activity *MarketingActivity `thrift:"activity,1" frugal:"1,default,MarketingActivity" json:"activity"`
	BaseResp *base.BaseResp     `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewGetActivityResp() *GetActivityResp {
	return &GetActivityResp{}
}

func (p *GetActivityResp) InitDefault() {
}

var GetActivityResp_Activity_DEFAULT *MarketingActivity

func (p *GetActivityResp) GetActivity() (v *MarketingActivity) {
	if !p.IsSetActivity() {
		return GetActivityResp_Activity_DEFAULT
	}
	return p.Activity
}

var GetActivityResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetActivityResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetActivityResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetActivityResp) SetActivity(val *MarketingActivity) {
	p.Activity = val
}
func (p *GetActivityResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetActivityResp) IsSetActivity() bool {
	return p.Activity != nil
}

func (p *GetActivityResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetActivityResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetActivityResp(%+v)", *p)
}

var fieldIDToName_GetActivityResp = map[int16]string{
	1:   "activity",
	255: "baseResp",
}

type ListCouponReq struct {
	ActivityId int64 `thrift:"activity_id,1" frugal:"1,default,i64" json:"activity_id"`
	Status     int32 `thrift:"status,2" frugal:"2,default,i32" json:"status"`
	Page       int32 `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize   int32 `thrift:"page_size,4" frugal:"4,default,i32" json:"page_size"`
}

func NewListCouponReq() *ListCouponReq {
	return &ListCouponReq{}
}

func (p *ListCouponReq) InitDefault() {
}

func (p *ListCouponReq) GetActivityId() (v int64) {
	return p.ActivityId
}

func (p *ListCouponReq) GetStatus() (v int32) {
	return p.Status
}

func (p *ListCouponReq) GetPage() (v int32) {
	return p.Page
}

func (p *ListCouponReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *ListCouponReq) SetActivityId(val int64) {
	p.ActivityId = val
}
func (p *ListCouponReq) SetStatus(val int32) {
	p.Status = val
}
func (p *ListCouponReq) SetPage(val int32) {
	p.Page = val
}
func (p *ListCouponReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *ListCouponReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListCouponReq(%+v)", *p)
}

var fieldIDToName_ListCouponReq = map[int16]string{
	1: "activity_id",
	2: "status",
	3: "page",
	4: "page_size",
}

type ListCouponResp struct {
	Coupons  []*Coupon      `thrift:"coupons,1" frugal:"1,default,list<Coupon>" json:"coupons"`
	Total    int64          `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewListCouponResp() *ListCouponResp {
	return &ListCouponResp{}
}

func (p *ListCouponResp) InitDefault() {
}

func (p *ListCouponResp) GetCoupons() (v []*Coupon) {
	return p.Coupons
}

func (p *ListCouponResp) GetTotal() (v int64) {
	return p.Total
}

var ListCouponResp_BaseResp_DEFAULT *base.BaseResp

func (p *ListCouponResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListCouponResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListCouponResp) SetCoupons(val []*Coupon) {
	p.Coupons = val
}
func (p *ListCouponResp) SetTotal(val int64) {
	p.Total = val
}
func (p *ListCouponResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListCouponResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListCouponResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListCouponResp(%+v)", *p)
}

var fieldIDToName_ListCouponResp = map[int16]string{
	1:   "coupons",
	2:   "total",
	255: "baseResp",
}

type IssueCouponReq struct {
	CouponId     int64   `thrift:"coupon_id,1" frugal:"1,default,i64" json:"coupon_id"`
	PassengerIds []int64 `thrift:"passenger_ids,2" frugal:"2,default,list<i64>" json:"passenger_ids"`
	IssueReason  string  `thrift:"issue_reason,3" frugal:"3,default,string" json:"issue_reason"`
}

func NewIssueCouponReq() *IssueCouponReq {
	return &IssueCouponReq{}
}

func (p *IssueCouponReq) InitDefault() {
}

func (p *IssueCouponReq) GetCouponId() (v int64) {
	return p.CouponId
}

func (p *IssueCouponReq) GetPassengerIds() (v []int64) {
	return p.PassengerIds
}

func (p *IssueCouponReq) GetIssueReason() (v string) {
	return p.IssueReason
}
func (p *IssueCouponReq) SetCouponId(val int64) {
	p.CouponId = val
}
func (p *IssueCouponReq) SetPassengerIds(val []int64) {
	p.PassengerIds = val
}
func (p *IssueCouponReq) SetIssueReason(val string) {
	p.IssueReason = val
}

func (p *IssueCouponReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IssueCouponReq(%+v)", *p)
}

var fieldIDToName_IssueCouponReq = map[int16]string{
	1: "coupon_id",
	2: "passenger_ids",
	3: "issue_reason",
}

type IssueCouponResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewIssueCouponResp() *IssueCouponResp {
	return &IssueCouponResp{}
}

func (p *IssueCouponResp) InitDefault() {
}

var IssueCouponResp_BaseResp_DEFAULT *base.BaseResp

func (p *IssueCouponResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return IssueCouponResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *IssueCouponResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *IssueCouponResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *IssueCouponResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IssueCouponResp(%+v)", *p)
}

var fieldIDToName_IssueCouponResp = map[int16]string{
	255: "baseResp",
}

type MarketingService interface {
	ListActivity(ctx context.Context, req *ListActivityReq) (r *ListActivityResp, err error)

	GetActivity(ctx context.Context, req *GetActivityReq) (r *GetActivityResp, err error)

	ListCoupon(ctx context.Context, req *ListCouponReq) (r *ListCouponResp, err error)

	IssueCoupon(ctx context.Context, req *IssueCouponReq) (r *IssueCouponResp, err error)
}

type MarketingServiceListActivityArgs struct {
	Req *ListActivityReq `thrift:"req,1" frugal:"1,default,ListActivityReq" json:"req"`
}

func NewMarketingServiceListActivityArgs() *MarketingServiceListActivityArgs {
	return &MarketingServiceListActivityArgs{}
}

func (p *MarketingServiceListActivityArgs) InitDefault() {
}

var MarketingServiceListActivityArgs_Req_DEFAULT *ListActivityReq

func (p *MarketingServiceListActivityArgs) GetReq() (v *ListActivityReq) {
	if !p.IsSetReq() {
		return MarketingServiceListActivityArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MarketingServiceListActivityArgs) SetReq(val *ListActivityReq) {
	p.Req = val
}

func (p *MarketingServiceListActivityArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MarketingServiceListActivityArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarketingServiceListActivityArgs(%+v)", *p)
}

var fieldIDToName_MarketingServiceListActivityArgs = map[int16]string{
	1: "req",
}

type MarketingServiceListActivityResult struct {
	Success *ListActivityResp `thrift:"success,0,optional" frugal:"0,optional,ListActivityResp" json:"success,omitempty"`
}

func NewMarketingServiceListActivityResult() *MarketingServiceListActivityResult {
	return &MarketingServiceListActivityResult{}
}

func (p *MarketingServiceListActivityResult) InitDefault() {
}

var MarketingServiceListActivityResult_Success_DEFAULT *ListActivityResp

func (p *MarketingServiceListActivityResult) GetSuccess() (v *ListActivityResp) {
	if !p.IsSetSuccess() {
		return MarketingServiceListActivityResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MarketingServiceListActivityResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListActivityResp)
}

func (p *MarketingServiceListActivityResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MarketingServiceListActivityResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarketingServiceListActivityResult(%+v)", *p)
}

var fieldIDToName_MarketingServiceListActivityResult = map[int16]string{
	0: "success",
}

type MarketingServiceGetActivityArgs struct {
	Req *GetActivityReq `thrift:"req,1" frugal:"1,default,GetActivityReq" json:"req"`
}

func NewMarketingServiceGetActivityArgs() *MarketingServiceGetActivityArgs {
	return &MarketingServiceGetActivityArgs{}
}

func (p *MarketingServiceGetActivityArgs) InitDefault() {
}

var MarketingServiceGetActivityArgs_Req_DEFAULT *GetActivityReq

func (p *MarketingServiceGetActivityArgs) GetReq() (v *GetActivityReq) {
	if !p.IsSetReq() {
		return MarketingServiceGetActivityArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MarketingServiceGetActivityArgs) SetReq(val *GetActivityReq) {
	p.Req = val
}

func (p *MarketingServiceGetActivityArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MarketingServiceGetActivityArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarketingServiceGetActivityArgs(%+v)", *p)
}

var fieldIDToName_MarketingServiceGetActivityArgs = map[int16]string{
	1: "req",
}

type MarketingServiceGetActivityResult struct {
	Success *GetActivityResp `thrift:"success,0,optional" frugal:"0,optional,GetActivityResp" json:"success,omitempty"`
}

func NewMarketingServiceGetActivityResult() *MarketingServiceGetActivityResult {
	return &MarketingServiceGetActivityResult{}
}

func (p *MarketingServiceGetActivityResult) InitDefault() {
}

var MarketingServiceGetActivityResult_Success_DEFAULT *GetActivityResp

func (p *MarketingServiceGetActivityResult) GetSuccess() (v *GetActivityResp) {
	if !p.IsSetSuccess() {
		return MarketingServiceGetActivityResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MarketingServiceGetActivityResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetActivityResp)
}

func (p *MarketingServiceGetActivityResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MarketingServiceGetActivityResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarketingServiceGetActivityResult(%+v)", *p)
}

var fieldIDToName_MarketingServiceGetActivityResult = map[int16]string{
	0: "success",
}

type MarketingServiceListCouponArgs struct {
	Req *ListCouponReq `thrift:"req,1" frugal:"1,default,ListCouponReq" json:"req"`
}

func NewMarketingServiceListCouponArgs() *MarketingServiceListCouponArgs {
	return &MarketingServiceListCouponArgs{}
}

func (p *MarketingServiceListCouponArgs) InitDefault() {
}

var MarketingServiceListCouponArgs_Req_DEFAULT *ListCouponReq

func (p *MarketingServiceListCouponArgs) GetReq() (v *ListCouponReq) {
	if !p.IsSetReq() {
		return MarketingServiceListCouponArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MarketingServiceListCouponArgs) SetReq(val *ListCouponReq) {
	p.Req = val
}

func (p *MarketingServiceListCouponArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MarketingServiceListCouponArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarketingServiceListCouponArgs(%+v)", *p)
}

var fieldIDToName_MarketingServiceListCouponArgs = map[int16]string{
	1: "req",
}

type MarketingServiceListCouponResult struct {
	Success *ListCouponResp `thrift:"success,0,optional" frugal:"0,optional,ListCouponResp" json:"success,omitempty"`
}

func NewMarketingServiceListCouponResult() *MarketingServiceListCouponResult {
	return &MarketingServiceListCouponResult{}
}

func (p *MarketingServiceListCouponResult) InitDefault() {
}

var MarketingServiceListCouponResult_Success_DEFAULT *ListCouponResp

func (p *MarketingServiceListCouponResult) GetSuccess() (v *ListCouponResp) {
	if !p.IsSetSuccess() {
		return MarketingServiceListCouponResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MarketingServiceListCouponResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListCouponResp)
}

func (p *MarketingServiceListCouponResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MarketingServiceListCouponResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarketingServiceListCouponResult(%+v)", *p)
}

var fieldIDToName_MarketingServiceListCouponResult = map[int16]string{
	0: "success",
}

type MarketingServiceIssueCouponArgs struct {
	Req *IssueCouponReq `thrift:"req,1" frugal:"1,default,IssueCouponReq" json:"req"`
}

func NewMarketingServiceIssueCouponArgs() *MarketingServiceIssueCouponArgs {
	return &MarketingServiceIssueCouponArgs{}
}

func (p *MarketingServiceIssueCouponArgs) InitDefault() {
}

var MarketingServiceIssueCouponArgs_Req_DEFAULT *IssueCouponReq

func (p *MarketingServiceIssueCouponArgs) GetReq() (v *IssueCouponReq) {
	if !p.IsSetReq() {
		return MarketingServiceIssueCouponArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MarketingServiceIssueCouponArgs) SetReq(val *IssueCouponReq) {
	p.Req = val
}

func (p *MarketingServiceIssueCouponArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MarketingServiceIssueCouponArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarketingServiceIssueCouponArgs(%+v)", *p)
}

var fieldIDToName_MarketingServiceIssueCouponArgs = map[int16]string{
	1: "req",
}

type MarketingServiceIssueCouponResult struct {
	Success *IssueCouponResp `thrift:"success,0,optional" frugal:"0,optional,IssueCouponResp" json:"success,omitempty"`
}

func NewMarketingServiceIssueCouponResult() *MarketingServiceIssueCouponResult {
	return &MarketingServiceIssueCouponResult{}
}

func (p *MarketingServiceIssueCouponResult) InitDefault() {
}

var MarketingServiceIssueCouponResult_Success_DEFAULT *IssueCouponResp

func (p *MarketingServiceIssueCouponResult) GetSuccess() (v *IssueCouponResp) {
	if !p.IsSetSuccess() {
		return MarketingServiceIssueCouponResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MarketingServiceIssueCouponResult) SetSuccess(x interface{}) {
	p.Success = x.(*IssueCouponResp)
}

func (p *MarketingServiceIssueCouponResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MarketingServiceIssueCouponResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarketingServiceIssueCouponResult(%+v)", *p)
}

var fieldIDToName_MarketingServiceIssueCouponResult = map[int16]string{
	0: "success",
}
