// Code generated by Kitex v0.16.1. DO NOT EDIT.

package dashboardservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	dashboard "hxzCar-admin/kitex_gen/hxzcar/dashboard"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetOverview(ctx context.Context, req *dashboard.GetOverviewReq, callOptions ...callopt.Option) (r *dashboard.GetOverviewResp, err error)
	GetOrderTrend(ctx context.Context, req *dashboard.GetOrderTrendReq, callOptions ...callopt.Option) (r *dashboard.GetOrderTrendResp, err error)
	GetCitySupply(ctx context.Context, req *dashboard.GetCitySupplyReq, callOptions ...callopt.Option) (r *dashboard.GetCitySupplyResp, err error)
	GetOrderFlow(ctx context.Context, req *dashboard.GetOrderFlowReq, callOptions ...callopt.Option) (r *dashboard.GetOrderFlowResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDashboardServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDashboardServiceClient struct {
	*kClient
}

func (p *kDashboardServiceClient) GetOverview(ctx context.Context, req *dashboard.GetOverviewReq, callOptions ...callopt.Option) (r *dashboard.GetOverviewResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOverview(ctx, req)
}

func (p *kDashboardServiceClient) GetOrderTrend(ctx context.Context, req *dashboard.GetOrderTrendReq, callOptions ...callopt.Option) (r *dashboard.GetOrderTrendResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrderTrend(ctx, req)
}

func (p *kDashboardServiceClient) GetCitySupply(ctx context.Context, req *dashboard.GetCitySupplyReq, callOptions ...callopt.Option) (r *dashboard.GetCitySupplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCitySupply(ctx, req)
}

func (p *kDashboardServiceClient) GetOrderFlow(ctx context.Context, req *dashboard.GetOrderFlowReq, callOptions ...callopt.Option) (r *dashboard.GetOrderFlowResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrderFlow(ctx, req)
}
