// Code generated by Kitex v0.16.1. DO NOT EDIT.

package dashboardservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	dashboard "hxzCar-admin/kitex_gen/hxzcar/dashboard"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetOverview": kitex.NewMethodInfo(
		getOverviewHandler,
		newDashboardServiceGetOverviewArgs,
		newDashboardServiceGetOverviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrderTrend": kitex.NewMethodInfo(
		getOrderTrendHandler,
		newDashboardServiceGetOrderTrendArgs,
		newDashboardServiceGetOrderTrendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCitySupply": kitex.NewMethodInfo(
		getCitySupplyHandler,
		newDashboardServiceGetCitySupplyArgs,
		newDashboardServiceGetCitySupplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrderFlow": kitex.NewMethodInfo(
		getOrderFlowHandler,
		newDashboardServiceGetOrderFlowArgs,
		newDashboardServiceGetOrderFlowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	dashboardServiceServiceInfo                = NewServiceInfo()
	dashboardServiceServiceInfoForClient       = NewServiceInfoForClient()
	dashboardServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return dashboardServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return dashboardServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return dashboardServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DashboardService"
	handlerType := (*dashboard.DashboardService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "dashboard",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getOverviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*dashboard.DashboardServiceGetOverviewArgs)
	realResult := result.(*dashboard.DashboardServiceGetOverviewResult)
	success, err := handler.(dashboard.DashboardService).GetOverview(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDashboardServiceGetOverviewArgs() interface{} {
	return dashboard.NewDashboardServiceGetOverviewArgs()
}

func newDashboardServiceGetOverviewResult() interface{} {
	return dashboard.NewDashboardServiceGetOverviewResult()
}

func getOrderTrendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*dashboard.DashboardServiceGetOrderTrendArgs)
	realResult := result.(*dashboard.DashboardServiceGetOrderTrendResult)
	success, err := handler.(dashboard.DashboardService).GetOrderTrend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDashboardServiceGetOrderTrendArgs() interface{} {
	return dashboard.NewDashboardServiceGetOrderTrendArgs()
}

func newDashboardServiceGetOrderTrendResult() interface{} {
	return dashboard.NewDashboardServiceGetOrderTrendResult()
}

func getCitySupplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*dashboard.DashboardServiceGetCitySupplyArgs)
	realResult := result.(*dashboard.DashboardServiceGetCitySupplyResult)
	success, err := handler.(dashboard.DashboardService).GetCitySupply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDashboardServiceGetCitySupplyArgs() interface{} {
	return dashboard.NewDashboardServiceGetCitySupplyArgs()
}

func newDashboardServiceGetCitySupplyResult() interface{} {
	return dashboard.NewDashboardServiceGetCitySupplyResult()
}

func getOrderFlowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*dashboard.DashboardServiceGetOrderFlowArgs)
	realResult := result.(*dashboard.DashboardServiceGetOrderFlowResult)
	success, err := handler.(dashboard.DashboardService).GetOrderFlow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDashboardServiceGetOrderFlowArgs() interface{} {
	return dashboard.NewDashboardServiceGetOrderFlowArgs()
}

func newDashboardServiceGetOrderFlowResult() interface{} {
	return dashboard.NewDashboardServiceGetOrderFlowResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetOverview(ctx context.Context, req *dashboard.GetOverviewReq) (r *dashboard.GetOverviewResp, err error) {
	var _args dashboard.DashboardServiceGetOverviewArgs
	_args.Req = req
	var _result dashboard.DashboardServiceGetOverviewResult
	if err = p.c.Call(ctx, "GetOverview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrderTrend(ctx context.Context, req *dashboard.GetOrderTrendReq) (r *dashboard.GetOrderTrendResp, err error) {
	var _args dashboard.DashboardServiceGetOrderTrendArgs
	_args.Req = req
	var _result dashboard.DashboardServiceGetOrderTrendResult
	if err = p.c.Call(ctx, "GetOrderTrend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCitySupply(ctx context.Context, req *dashboard.GetCitySupplyReq) (r *dashboard.GetCitySupplyResp, err error) {
	var _args dashboard.DashboardServiceGetCitySupplyArgs
	_args.Req = req
	var _result dashboard.DashboardServiceGetCitySupplyResult
	if err = p.c.Call(ctx, "GetCitySupply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrderFlow(ctx context.Context, req *dashboard.GetOrderFlowReq) (r *dashboard.GetOrderFlowResp, err error) {
	var _args dashboard.DashboardServiceGetOrderFlowArgs
	_args.Req = req
	var _result dashboard.DashboardServiceGetOrderFlowResult
	if err = p.c.Call(ctx, "GetOrderFlow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
