// Code generated by Kitex v0.16.1. DO NOT EDIT.

package driverservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	driver0 "hxzCar-admin/kitex_gen/hxzcar/driver"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListDriver(ctx context.Context, req *driver0.ListDriverReq, callOptions ...callopt.Option) (r *driver0.ListDriverResp, err error)
	GetDriver(ctx context.Context, req *driver0.GetDriverReq, callOptions ...callopt.Option) (r *driver0.GetDriverResp, err error)
	UpdateDriverStatus(ctx context.Context, req *driver0.UpdateDriverStatusReq, callOptions ...callopt.Option) (r *driver0.UpdateDriverStatusResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDriverServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDriverServiceClient struct {
	*kClient
}

func (p *kDriverServiceClient) ListDriver(ctx context.Context, req *driver0.ListDriverReq, callOptions ...callopt.Option) (r *driver0.ListDriverResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListDriver(ctx, req)
}

func (p *kDriverServiceClient) GetDriver(ctx context.Context, req *driver0.GetDriverReq, callOptions ...callopt.Option) (r *driver0.GetDriverResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDriver(ctx, req)
}

func (p *kDriverServiceClient) UpdateDriverStatus(ctx context.Context, req *driver0.UpdateDriverStatusReq, callOptions ...callopt.Option) (r *driver0.UpdateDriverStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateDriverStatus(ctx, req)
}
