// Code generated by Kitex v0.16.1. DO NOT EDIT.

package complaintservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	complaint "hxzCar-admin/kitex_gen/hxzcar/complaint"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListComplaint(ctx context.Context, req *complaint.ListComplaintReq, callOptions ...callopt.Option) (r *complaint.ListComplaintResp, err error)
	GetComplaint(ctx context.Context, req *complaint.GetComplaintReq, callOptions ...callopt.Option) (r *complaint.GetComplaintResp, err error)
	ResolveComplaint(ctx context.Context, req *complaint.ResolveComplaintReq, callOptions ...callopt.Option) (r *complaint.ResolveComplaintResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kComplaintServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kComplaintServiceClient struct {
	*kClient
}

func (p *kComplaintServiceClient) ListComplaint(ctx context.Context, req *complaint.ListComplaintReq, callOptions ...callopt.Option) (r *complaint.ListComplaintResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListComplaint(ctx, req)
}

func (p *kComplaintServiceClient) GetComplaint(ctx context.Context, req *complaint.GetComplaintReq, callOptions ...callopt.Option) (r *complaint.GetComplaintResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetComplaint(ctx, req)
}

func (p *kComplaintServiceClient) ResolveComplaint(ctx context.Context, req *complaint.ResolveComplaintReq, callOptions ...callopt.Option) (r *complaint.ResolveComplaintResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResolveComplaint(ctx, req)
}
