// Code generated by Kitex v0.16.1. DO NOT EDIT.
package complaintservice

import (
	server "github.com/cloudwego/kitex/server"
	complaint "hxzCar-admin/kitex_gen/hxzcar/complaint"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler complaint.ComplaintService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler complaint.ComplaintService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
