// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"hxzCar-admin/kitex_gen/hxzcar/base"
)

type User struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Username  string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Phone     string `thrift:"phone,3" frugal:"3,default,string" json:"phone"`
	Role      string `thrift:"role,4" frugal:"4,default,string" json:"role"`
	Status    int32  `thrift:"status,5" frugal:"5,default,i32" json:"status"`
	CreatedAt string `thrift:"created_at,6" frugal:"6,default,string" json:"created_at"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetPhone() (v string) {
	return p.Phone
}

func (p *User) GetRole() (v string) {
	return p.Role
}

func (p *User) GetStatus() (v int32) {
	return p.Status
}

func (p *User) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetPhone(val string) {
	p.Phone = val
}
func (p *User) SetRole(val string) {
	p.Role = val
}
func (p *User) SetStatus(val int32) {
	p.Status = val
}
func (p *User) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "id",
	2: "username",
	3: "phone",
	4: "role",
	5: "status",
	6: "created_at",
}

type RegisterReq struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Phone    string `thrift:"phone,2" frugal:"2,default,string" json:"phone"`
	Password string `thrift:"password,3" frugal:"3,default,string" json:"password"`
	Role     string `thrift:"role,4" frugal:"4,default,string" json:"role"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterReq) GetPhone() (v string) {
	return p.Phone
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterReq) GetRole() (v string) {
	return p.Role
}
func (p *RegisterReq) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterReq) SetPhone(val string) {
	p.Phone = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterReq) SetRole(val string) {
	p.Role = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "username",
	2: "phone",
	3: "password",
	4: "role",
}

type RegisterResp struct {
	User     *User          `thrift:"user,1" frugal:"1,default,User" json:"user"`
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

var RegisterResp_User_DEFAULT *User

func (p *RegisterResp) GetUser() (v *User) {
	if !p.IsSetUser() {
		return RegisterResp_User_DEFAULT
	}
	return p.User
}

var RegisterResp_BaseResp_DEFAULT *base.BaseResp

func (p *RegisterResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return RegisterResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *RegisterResp) SetUser(val *User) {
	p.User = val
}
func (p *RegisterResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *RegisterResp) IsSetUser() bool {
	return p.User != nil
}

func (p *RegisterResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1:   "user",
	255: "baseResp",
}

type GetUserReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetUserReq() *GetUserReq {
	return &GetUserReq{}
}

func (p *GetUserReq) InitDefault() {
}

func (p *GetUserReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserReq(%+v)", *p)
}

var fieldIDToName_GetUserReq = map[int16]string{
	1: "user_id",
}

type GetUserResp struct {
	User     *User          `thrift:"user,1" frugal:"1,default,User" json:"user"`
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewGetUserResp() *GetUserResp {
	return &GetUserResp{}
}

func (p *GetUserResp) InitDefault() {
}

var GetUserResp_User_DEFAULT *User

func (p *GetUserResp) GetUser() (v *User) {
	if !p.IsSetUser() {
		return GetUserResp_User_DEFAULT
	}
	return p.User
}

var GetUserResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetUserResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetUserResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetUserResp) SetUser(val *User) {
	p.User = val
}
func (p *GetUserResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetUserResp) IsSetUser() bool {
	return p.User != nil
}

func (p *GetUserResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserResp(%+v)", *p)
}

var fieldIDToName_GetUserResp = map[int16]string{
	1:   "user",
	255: "baseResp",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	GetUser(ctx context.Context, req *GetUserReq) (r *GetUserResp, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserArgs struct {
	Req *GetUserReq `thrift:"req,1" frugal:"1,default,GetUserReq" json:"req"`
}

func NewUserServiceGetUserArgs() *UserServiceGetUserArgs {
	return &UserServiceGetUserArgs{}
}

func (p *UserServiceGetUserArgs) InitDefault() {
}

var UserServiceGetUserArgs_Req_DEFAULT *GetUserReq

func (p *UserServiceGetUserArgs) GetReq() (v *GetUserReq) {
	if !p.IsSetReq() {
		return UserServiceGetUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserArgs) SetReq(val *GetUserReq) {
	p.Req = val
}

func (p *UserServiceGetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserResult struct {
	Success *GetUserResp `thrift:"success,0,optional" frugal:"0,optional,GetUserResp" json:"success,omitempty"`
}

func NewUserServiceGetUserResult() *UserServiceGetUserResult {
	return &UserServiceGetUserResult{}
}

func (p *UserServiceGetUserResult) InitDefault() {
}

var UserServiceGetUserResult_Success_DEFAULT *GetUserResp

func (p *UserServiceGetUserResult) GetSuccess() (v *GetUserResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserResp)
}

func (p *UserServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserResult = map[int16]string{
	0: "success",
}
