// Code generated by Kitex v0.16.1. DO NOT EDIT.

package pricingservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	pricing "hxzCar-admin/kitex_gen/hxzcar/pricing"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListRule": kitex.NewMethodInfo(
		listRuleHandler,
		newPricingServiceListRuleArgs,
		newPricingServiceListRuleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetRule": kitex.NewMethodInfo(
		getRuleHandler,
		newPricingServiceGetRuleArgs,
		newPricingServiceGetRuleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateRule": kitex.NewMethodInfo(
		createRuleHandler,
		newPricingServiceCreateRuleArgs,
		newPricingServiceCreateRuleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateRule": kitex.NewMethodInfo(
		updateRuleHandler,
		newPricingServiceUpdateRuleArgs,
		newPricingServiceUpdateRuleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteRule": kitex.NewMethodInfo(
		deleteRuleHandler,
		newPricingServiceDeleteRuleArgs,
		newPricingServiceDeleteRuleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	pricingServiceServiceInfo                = NewServiceInfo()
	pricingServiceServiceInfoForClient       = NewServiceInfoForClient()
	pricingServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return pricingServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return pricingServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return pricingServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PricingService"
	handlerType := (*pricing.PricingService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "pricing",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func listRuleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pricing.PricingServiceListRuleArgs)
	realResult := result.(*pricing.PricingServiceListRuleResult)
	success, err := handler.(pricing.PricingService).ListRule(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPricingServiceListRuleArgs() interface{} {
	return pricing.NewPricingServiceListRuleArgs()
}

func newPricingServiceListRuleResult() interface{} {
	return pricing.NewPricingServiceListRuleResult()
}

func getRuleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pricing.PricingServiceGetRuleArgs)
	realResult := result.(*pricing.PricingServiceGetRuleResult)
	success, err := handler.(pricing.PricingService).GetRule(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPricingServiceGetRuleArgs() interface{} {
	return pricing.NewPricingServiceGetRuleArgs()
}

func newPricingServiceGetRuleResult() interface{} {
	return pricing.NewPricingServiceGetRuleResult()
}

func createRuleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pricing.PricingServiceCreateRuleArgs)
	realResult := result.(*pricing.PricingServiceCreateRuleResult)
	success, err := handler.(pricing.PricingService).CreateRule(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPricingServiceCreateRuleArgs() interface{} {
	return pricing.NewPricingServiceCreateRuleArgs()
}

func newPricingServiceCreateRuleResult() interface{} {
	return pricing.NewPricingServiceCreateRuleResult()
}

func updateRuleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pricing.PricingServiceUpdateRuleArgs)
	realResult := result.(*pricing.PricingServiceUpdateRuleResult)
	success, err := handler.(pricing.PricingService).UpdateRule(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPricingServiceUpdateRuleArgs() interface{} {
	return pricing.NewPricingServiceUpdateRuleArgs()
}

func newPricingServiceUpdateRuleResult() interface{} {
	return pricing.NewPricingServiceUpdateRuleResult()
}

func deleteRuleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pricing.PricingServiceDeleteRuleArgs)
	realResult := result.(*pricing.PricingServiceDeleteRuleResult)
	success, err := handler.(pricing.PricingService).DeleteRule(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPricingServiceDeleteRuleArgs() interface{} {
	return pricing.NewPricingServiceDeleteRuleArgs()
}

func newPricingServiceDeleteRuleResult() interface{} {
	return pricing.NewPricingServiceDeleteRuleResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListRule(ctx context.Context, req *pricing.ListRuleReq) (r *pricing.ListRuleResp, err error) {
	var _args pricing.PricingServiceListRuleArgs
	_args.Req = req
	var _result pricing.PricingServiceListRuleResult
	if err = p.c.Call(ctx, "ListRule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRule(ctx context.Context, req *pricing.GetRuleReq) (r *pricing.GetRuleResp, err error) {
	var _args pricing.PricingServiceGetRuleArgs
	_args.Req = req
	var _result pricing.PricingServiceGetRuleResult
	if err = p.c.Call(ctx, "GetRule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateRule(ctx context.Context, req *pricing.CreateRuleReq) (r *pricing.CreateRuleResp, err error) {
	var _args pricing.PricingServiceCreateRuleArgs
	_args.Req = req
	var _result pricing.PricingServiceCreateRuleResult
	if err = p.c.Call(ctx, "CreateRule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateRule(ctx context.Context, req *pricing.UpdateRuleReq) (r *pricing.UpdateRuleResp, err error) {
	var _args pricing.PricingServiceUpdateRuleArgs
	_args.Req = req
	var _result pricing.PricingServiceUpdateRuleResult
	if err = p.c.Call(ctx, "UpdateRule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteRule(ctx context.Context, req *pricing.DeleteRuleReq) (r *pricing.DeleteRuleResp, err error) {
	var _args pricing.PricingServiceDeleteRuleArgs
	_args.Req = req
	var _result pricing.PricingServiceDeleteRuleResult
	if err = p.c.Call(ctx, "DeleteRule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
