// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package analytics

import (
	"context"
	"fmt"
	"hxzCar-admin/kitex_gen/hxzcar/base"
)

type AnalyticsOverview struct {
	TotalOrders      int64   `thrift:"total_orders,1" frugal:"1,default,i64" json:"total_orders"`
	Gmv              float64 `thrift:"gmv,2" frugal:"2,default,double" json:"gmv"`
	CompletionRate   float64 `thrift:"completion_rate,3" frugal:"3,default,double" json:"completion_rate"`
	CancellationRate float64 `thrift:"cancellation_rate,4" frugal:"4,default,double" json:"cancellation_rate"`
	NewUsers_        int64   `thrift:"new_users,5" frugal:"5,default,i64" json:"new_users"`
	ActiveUsers      int64   `thrift:"active_users,6" frugal:"6,default,i64" json:"active_users"`
}

func NewAnalyticsOverview() *AnalyticsOverview {
	return &AnalyticsOverview{}
}

func (p *AnalyticsOverview) InitDefault() {
}

func (p *AnalyticsOverview) GetTotalOrders() (v int64) {
	return p.TotalOrders
}

func (p *AnalyticsOverview) GetGmv() (v float64) {
	return p.Gmv
}

func (p *AnalyticsOverview) GetCompletionRate() (v float64) {
	return p.CompletionRate
}

func (p *AnalyticsOverview) GetCancellationRate() (v float64) {
	return p.CancellationRate
}

func (p *AnalyticsOverview) GetNewUsers_() (v int64) {
	return p.NewUsers_
}

func (p *AnalyticsOverview) GetActiveUsers() (v int64) {
	return p.ActiveUsers
}
func (p *AnalyticsOverview) SetTotalOrders(val int64) {
	p.TotalOrders = val
}
func (p *AnalyticsOverview) SetGmv(val float64) {
	p.Gmv = val
}
func (p *AnalyticsOverview) SetCompletionRate(val float64) {
	p.CompletionRate = val
}
func (p *AnalyticsOverview) SetCancellationRate(val float64) {
	p.CancellationRate = val
}
func (p *AnalyticsOverview) SetNewUsers_(val int64) {
	p.NewUsers_ = val
}
func (p *AnalyticsOverview) SetActiveUsers(val int64) {
	p.ActiveUsers = val
}

func (p *AnalyticsOverview) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyticsOverview(%+v)", *p)
}

var fieldIDToName_AnalyticsOverview = map[int16]string{
	1: "total_orders",
	2: "gmv",
	3: "completion_rate",
	4: "cancellation_rate",
	5: "new_users",
	6: "active_users",
}

type OrderDistribution struct {
	Hour  string `thrift:"hour,1" frugal:"1,default,string" json:"hour"`
	Count int32  `thrift:"count,2" frugal:"2,default,i32" json:"count"`
	Level string `thrift:"level,3" frugal:"3,default,string" json:"level"`
}

func NewOrderDistribution() *OrderDistribution {
	return &OrderDistribution{}
}

func (p *OrderDistribution) InitDefault() {
}

func (p *OrderDistribution) GetHour() (v string) {
	return p.Hour
}

func (p *OrderDistribution) GetCount() (v int32) {
	return p.Count
}

func (p *OrderDistribution) GetLevel() (v string) {
	return p.Level
}
func (p *OrderDistribution) SetHour(val string) {
	p.Hour = val
}
func (p *OrderDistribution) SetCount(val int32) {
	p.Count = val
}
func (p *OrderDistribution) SetLevel(val string) {
	p.Level = val
}

func (p *OrderDistribution) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderDistribution(%+v)", *p)
}

var fieldIDToName_OrderDistribution = map[int16]string{
	1: "hour",
	2: "count",
	3: "level",
}

type IncomeTrend struct {
	Date   string  `thrift:"date,1" frugal:"1,default,string" json:"date"`
	Income float64 `thrift:"income,2" frugal:"2,default,double" json:"income"`
}

func NewIncomeTrend() *IncomeTrend {
	return &IncomeTrend{}
}

func (p *IncomeTrend) InitDefault() {
}

func (p *IncomeTrend) GetDate() (v string) {
	return p.Date
}

func (p *IncomeTrend) GetIncome() (v float64) {
	return p.Income
}
func (p *IncomeTrend) SetDate(val string) {
	p.Date = val
}
func (p *IncomeTrend) SetIncome(val float64) {
	p.Income = val
}

func (p *IncomeTrend) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IncomeTrend(%+v)", *p)
}

var fieldIDToName_IncomeTrend = map[int16]string{
	1: "date",
	2: "income",
}

type UserDistribution struct {
	Type  string  `thrift:"type,1" frugal:"1,default,string" json:"type"`
	Count int32   `thrift:"count,2" frugal:"2,default,i32" json:"count"`
	Ratio float64 `thrift:"ratio,3" frugal:"3,default,double" json:"ratio"`
}

func NewUserDistribution() *UserDistribution {
	return &UserDistribution{}
}

func (p *UserDistribution) InitDefault() {
}

func (p *UserDistribution) GetType() (v string) {
	return p.Type
}

func (p *UserDistribution) GetCount() (v int32) {
	return p.Count
}

func (p *UserDistribution) GetRatio() (v float64) {
	return p.Ratio
}
func (p *UserDistribution) SetType(val string) {
	p.Type = val
}
func (p *UserDistribution) SetCount(val int32) {
	p.Count = val
}
func (p *UserDistribution) SetRatio(val float64) {
	p.Ratio = val
}

func (p *UserDistribution) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserDistribution(%+v)", *p)
}

var fieldIDToName_UserDistribution = map[int16]string{
	1: "type",
	2: "count",
	3: "ratio",
}

type GetOverviewReq struct {
	Period string `thrift:"period,1" frugal:"1,default,string" json:"period"`
}

func NewGetOverviewReq() *GetOverviewReq {
	return &GetOverviewReq{}
}

func (p *GetOverviewReq) InitDefault() {
}

func (p *GetOverviewReq) GetPeriod() (v string) {
	return p.Period
}
func (p *GetOverviewReq) SetPeriod(val string) {
	p.Period = val
}

func (p *GetOverviewReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOverviewReq(%+v)", *p)
}

var fieldIDToName_GetOverviewReq = map[int16]string{
	1: "period",
}

type GetOverviewResp struct {
	Overview *AnalyticsOverview `thrift:"overview,1" frugal:"1,default,AnalyticsOverview" json:"overview"`
	BaseResp *base.BaseResp     `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewGetOverviewResp() *GetOverviewResp {
	return &GetOverviewResp{}
}

func (p *GetOverviewResp) InitDefault() {
}

var GetOverviewResp_Overview_DEFAULT *AnalyticsOverview

func (p *GetOverviewResp) GetOverview() (v *AnalyticsOverview) {
	if !p.IsSetOverview() {
		return GetOverviewResp_Overview_DEFAULT
	}
	return p.Overview
}

var GetOverviewResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetOverviewResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetOverviewResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetOverviewResp) SetOverview(val *AnalyticsOverview) {
	p.Overview = val
}
func (p *GetOverviewResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetOverviewResp) IsSetOverview() bool {
	return p.Overview != nil
}

func (p *GetOverviewResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetOverviewResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOverviewResp(%+v)", *p)
}

var fieldIDToName_GetOverviewResp = map[int16]string{
	1:   "overview",
	255: "baseResp",
}

type GetOrderDistributionReq struct {
}

func NewGetOrderDistributionReq() *GetOrderDistributionReq {
	return &GetOrderDistributionReq{}
}

func (p *GetOrderDistributionReq) InitDefault() {
}

func (p *GetOrderDistributionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderDistributionReq(%+v)", *p)
}

var fieldIDToName_GetOrderDistributionReq = map[int16]string{}

type GetOrderDistributionResp struct {
	Distributions []*OrderDistribution `thrift:"distributions,1" frugal:"1,default,list<OrderDistribution>" json:"distributions"`
	BaseResp      *base.BaseResp       `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewGetOrderDistributionResp() *GetOrderDistributionResp {
	return &GetOrderDistributionResp{}
}

func (p *GetOrderDistributionResp) InitDefault() {
}

func (p *GetOrderDistributionResp) GetDistributions() (v []*OrderDistribution) {
	return p.Distributions
}

var GetOrderDistributionResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetOrderDistributionResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetOrderDistributionResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetOrderDistributionResp) SetDistributions(val []*OrderDistribution) {
	p.Distributions = val
}
func (p *GetOrderDistributionResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetOrderDistributionResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetOrderDistributionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderDistributionResp(%+v)", *p)
}

var fieldIDToName_GetOrderDistributionResp = map[int16]string{
	1:   "distributions",
	255: "baseResp",
}

type GetIncomeTrendReq struct {
}

func NewGetIncomeTrendReq() *GetIncomeTrendReq {
	return &GetIncomeTrendReq{}
}

func (p *GetIncomeTrendReq) InitDefault() {
}

func (p *GetIncomeTrendReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetIncomeTrendReq(%+v)", *p)
}

var fieldIDToName_GetIncomeTrendReq = map[int16]string{}

type GetIncomeTrendResp struct {
	Trends   []*IncomeTrend `thrift:"trends,1" frugal:"1,default,list<IncomeTrend>" json:"trends"`
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewGetIncomeTrendResp() *GetIncomeTrendResp {
	return &GetIncomeTrendResp{}
}

func (p *GetIncomeTrendResp) InitDefault() {
}

func (p *GetIncomeTrendResp) GetTrends() (v []*IncomeTrend) {
	return p.Trends
}

var GetIncomeTrendResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetIncomeTrendResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetIncomeTrendResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetIncomeTrendResp) SetTrends(val []*IncomeTrend) {
	p.Trends = val
}
func (p *GetIncomeTrendResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetIncomeTrendResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetIncomeTrendResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetIncomeTrendResp(%+v)", *p)
}

var fieldIDToName_GetIncomeTrendResp = map[int16]string{
	1:   "trends",
	255: "baseResp",
}

type GetUserDistributionReq struct {
}

func NewGetUserDistributionReq() *GetUserDistributionReq {
	return &GetUserDistributionReq{}
}

func (p *GetUserDistributionReq) InitDefault() {
}

func (p *GetUserDistributionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserDistributionReq(%+v)", *p)
}

var fieldIDToName_GetUserDistributionReq = map[int16]string{}

type GetUserDistributionResp struct {
	Distributions []*UserDistribution `thrift:"distributions,1" frugal:"1,default,list<UserDistribution>" json:"distributions"`
	BaseResp      *base.BaseResp      `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewGetUserDistributionResp() *GetUserDistributionResp {
	return &GetUserDistributionResp{}
}

func (p *GetUserDistributionResp) InitDefault() {
}

func (p *GetUserDistributionResp) GetDistributions() (v []*UserDistribution) {
	return p.Distributions
}

var GetUserDistributionResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetUserDistributionResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetUserDistributionResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetUserDistributionResp) SetDistributions(val []*UserDistribution) {
	p.Distributions = val
}
func (p *GetUserDistributionResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetUserDistributionResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUserDistributionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserDistributionResp(%+v)", *p)
}

var fieldIDToName_GetUserDistributionResp = map[int16]string{
	1:   "distributions",
	255: "baseResp",
}

type AnalyticsService interface {
	GetOverview(ctx context.Context, req *GetOverviewReq) (r *GetOverviewResp, err error)

	GetOrderDistribution(ctx context.Context, req *GetOrderDistributionReq) (r *GetOrderDistributionResp, err error)

	GetIncomeTrend(ctx context.Context, req *GetIncomeTrendReq) (r *GetIncomeTrendResp, err error)

	GetUserDistribution(ctx context.Context, req *GetUserDistributionReq) (r *GetUserDistributionResp, err error)
}

type AnalyticsServiceGetOverviewArgs struct {
	Req *GetOverviewReq `thrift:"req,1" frugal:"1,default,GetOverviewReq" json:"req"`
}

func NewAnalyticsServiceGetOverviewArgs() *AnalyticsServiceGetOverviewArgs {
	return &AnalyticsServiceGetOverviewArgs{}
}

func (p *AnalyticsServiceGetOverviewArgs) InitDefault() {
}

var AnalyticsServiceGetOverviewArgs_Req_DEFAULT *GetOverviewReq

func (p *AnalyticsServiceGetOverviewArgs) GetReq() (v *GetOverviewReq) {
	if !p.IsSetReq() {
		return AnalyticsServiceGetOverviewArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AnalyticsServiceGetOverviewArgs) SetReq(val *GetOverviewReq) {
	p.Req = val
}

func (p *AnalyticsServiceGetOverviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AnalyticsServiceGetOverviewArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyticsServiceGetOverviewArgs(%+v)", *p)
}

var fieldIDToName_AnalyticsServiceGetOverviewArgs = map[int16]string{
	1: "req",
}

type AnalyticsServiceGetOverviewResult struct {
	Success *GetOverviewResp `thrift:"success,0,optional" frugal:"0,optional,GetOverviewResp" json:"success,omitempty"`
}

func NewAnalyticsServiceGetOverviewResult() *AnalyticsServiceGetOverviewResult {
	return &AnalyticsServiceGetOverviewResult{}
}

func (p *AnalyticsServiceGetOverviewResult) InitDefault() {
}

var AnalyticsServiceGetOverviewResult_Success_DEFAULT *GetOverviewResp

func (p *AnalyticsServiceGetOverviewResult) GetSuccess() (v *GetOverviewResp) {
	if !p.IsSetSuccess() {
		return AnalyticsServiceGetOverviewResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AnalyticsServiceGetOverviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOverviewResp)
}

func (p *AnalyticsServiceGetOverviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AnalyticsServiceGetOverviewResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyticsServiceGetOverviewResult(%+v)", *p)
}

var fieldIDToName_AnalyticsServiceGetOverviewResult = map[int16]string{
	0: "success",
}

type AnalyticsServiceGetOrderDistributionArgs struct {
	Req *GetOrderDistributionReq `thrift:"req,1" frugal:"1,default,GetOrderDistributionReq" json:"req"`
}

func NewAnalyticsServiceGetOrderDistributionArgs() *AnalyticsServiceGetOrderDistributionArgs {
	return &AnalyticsServiceGetOrderDistributionArgs{}
}

func (p *AnalyticsServiceGetOrderDistributionArgs) InitDefault() {
}

var AnalyticsServiceGetOrderDistributionArgs_Req_DEFAULT *GetOrderDistributionReq

func (p *AnalyticsServiceGetOrderDistributionArgs) GetReq() (v *GetOrderDistributionReq) {
	if !p.IsSetReq() {
		return AnalyticsServiceGetOrderDistributionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AnalyticsServiceGetOrderDistributionArgs) SetReq(val *GetOrderDistributionReq) {
	p.Req = val
}

func (p *AnalyticsServiceGetOrderDistributionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AnalyticsServiceGetOrderDistributionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyticsServiceGetOrderDistributionArgs(%+v)", *p)
}

var fieldIDToName_AnalyticsServiceGetOrderDistributionArgs = map[int16]string{
	1: "req",
}

type AnalyticsServiceGetOrderDistributionResult struct {
	Success *GetOrderDistributionResp `thrift:"success,0,optional" frugal:"0,optional,GetOrderDistributionResp" json:"success,omitempty"`
}

func NewAnalyticsServiceGetOrderDistributionResult() *AnalyticsServiceGetOrderDistributionResult {
	return &AnalyticsServiceGetOrderDistributionResult{}
}

func (p *AnalyticsServiceGetOrderDistributionResult) InitDefault() {
}

var AnalyticsServiceGetOrderDistributionResult_Success_DEFAULT *GetOrderDistributionResp

func (p *AnalyticsServiceGetOrderDistributionResult) GetSuccess() (v *GetOrderDistributionResp) {
	if !p.IsSetSuccess() {
		return AnalyticsServiceGetOrderDistributionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AnalyticsServiceGetOrderDistributionResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrderDistributionResp)
}

func (p *AnalyticsServiceGetOrderDistributionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AnalyticsServiceGetOrderDistributionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyticsServiceGetOrderDistributionResult(%+v)", *p)
}

var fieldIDToName_AnalyticsServiceGetOrderDistributionResult = map[int16]string{
	0: "success",
}

type AnalyticsServiceGetIncomeTrendArgs struct {
	Req *GetIncomeTrendReq `thrift:"req,1" frugal:"1,default,GetIncomeTrendReq" json:"req"`
}

func NewAnalyticsServiceGetIncomeTrendArgs() *AnalyticsServiceGetIncomeTrendArgs {
	return &AnalyticsServiceGetIncomeTrendArgs{}
}

func (p *AnalyticsServiceGetIncomeTrendArgs) InitDefault() {
}

var AnalyticsServiceGetIncomeTrendArgs_Req_DEFAULT *GetIncomeTrendReq

func (p *AnalyticsServiceGetIncomeTrendArgs) GetReq() (v *GetIncomeTrendReq) {
	if !p.IsSetReq() {
		return AnalyticsServiceGetIncomeTrendArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AnalyticsServiceGetIncomeTrendArgs) SetReq(val *GetIncomeTrendReq) {
	p.Req = val
}

func (p *AnalyticsServiceGetIncomeTrendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AnalyticsServiceGetIncomeTrendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyticsServiceGetIncomeTrendArgs(%+v)", *p)
}

var fieldIDToName_AnalyticsServiceGetIncomeTrendArgs = map[int16]string{
	1: "req",
}

type AnalyticsServiceGetIncomeTrendResult struct {
	Success *GetIncomeTrendResp `thrift:"success,0,optional" frugal:"0,optional,GetIncomeTrendResp" json:"success,omitempty"`
}

func NewAnalyticsServiceGetIncomeTrendResult() *AnalyticsServiceGetIncomeTrendResult {
	return &AnalyticsServiceGetIncomeTrendResult{}
}

func (p *AnalyticsServiceGetIncomeTrendResult) InitDefault() {
}

var AnalyticsServiceGetIncomeTrendResult_Success_DEFAULT *GetIncomeTrendResp

func (p *AnalyticsServiceGetIncomeTrendResult) GetSuccess() (v *GetIncomeTrendResp) {
	if !p.IsSetSuccess() {
		return AnalyticsServiceGetIncomeTrendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AnalyticsServiceGetIncomeTrendResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetIncomeTrendResp)
}

func (p *AnalyticsServiceGetIncomeTrendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AnalyticsServiceGetIncomeTrendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyticsServiceGetIncomeTrendResult(%+v)", *p)
}

var fieldIDToName_AnalyticsServiceGetIncomeTrendResult = map[int16]string{
	0: "success",
}

type AnalyticsServiceGetUserDistributionArgs struct {
	Req *GetUserDistributionReq `thrift:"req,1" frugal:"1,default,GetUserDistributionReq" json:"req"`
}

func NewAnalyticsServiceGetUserDistributionArgs() *AnalyticsServiceGetUserDistributionArgs {
	return &AnalyticsServiceGetUserDistributionArgs{}
}

func (p *AnalyticsServiceGetUserDistributionArgs) InitDefault() {
}

var AnalyticsServiceGetUserDistributionArgs_Req_DEFAULT *GetUserDistributionReq

func (p *AnalyticsServiceGetUserDistributionArgs) GetReq() (v *GetUserDistributionReq) {
	if !p.IsSetReq() {
		return AnalyticsServiceGetUserDistributionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AnalyticsServiceGetUserDistributionArgs) SetReq(val *GetUserDistributionReq) {
	p.Req = val
}

func (p *AnalyticsServiceGetUserDistributionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AnalyticsServiceGetUserDistributionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyticsServiceGetUserDistributionArgs(%+v)", *p)
}

var fieldIDToName_AnalyticsServiceGetUserDistributionArgs = map[int16]string{
	1: "req",
}

type AnalyticsServiceGetUserDistributionResult struct {
	Success *GetUserDistributionResp `thrift:"success,0,optional" frugal:"0,optional,GetUserDistributionResp" json:"success,omitempty"`
}

func NewAnalyticsServiceGetUserDistributionResult() *AnalyticsServiceGetUserDistributionResult {
	return &AnalyticsServiceGetUserDistributionResult{}
}

func (p *AnalyticsServiceGetUserDistributionResult) InitDefault() {
}

var AnalyticsServiceGetUserDistributionResult_Success_DEFAULT *GetUserDistributionResp

func (p *AnalyticsServiceGetUserDistributionResult) GetSuccess() (v *GetUserDistributionResp) {
	if !p.IsSetSuccess() {
		return AnalyticsServiceGetUserDistributionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AnalyticsServiceGetUserDistributionResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserDistributionResp)
}

func (p *AnalyticsServiceGetUserDistributionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AnalyticsServiceGetUserDistributionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyticsServiceGetUserDistributionResult(%+v)", *p)
}

var fieldIDToName_AnalyticsServiceGetUserDistributionResult = map[int16]string{
	0: "success",
}
