// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package driver

import (
	"context"
	"fmt"
	"hxzCar-admin/kitex_gen/hxzcar/base"
)

type Driver struct {
	Id           int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	DriverNo     string  `thrift:"driver_no,2" frugal:"2,default,string" json:"driver_no"`
	Name         string  `thrift:"name,3" frugal:"3,default,string" json:"name"`
	Phone        string  `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
	LicensePlate string  `thrift:"license_plate,5" frugal:"5,default,string" json:"license_plate"`
	CarModel     string  `thrift:"car_model,6" frugal:"6,default,string" json:"car_model"`
	Rating       float64 `thrift:"rating,7" frugal:"7,default,double" json:"rating"`
	TotalOrders  int32   `thrift:"total_orders,8" frugal:"8,default,i32" json:"total_orders"`
	TodayIncome  float64 `thrift:"today_income,9" frugal:"9,default,double" json:"today_income"`
	ServiceScore int32   `thrift:"service_score,10" frugal:"10,default,i32" json:"service_score"`
	AuditStatus  int32   `thrift:"audit_status,11" frugal:"11,default,i32" json:"audit_status"`
	OnlineStatus int32   `thrift:"online_status,12" frugal:"12,default,i32" json:"online_status"`
	CreateTime   string  `thrift:"create_time,13" frugal:"13,default,string" json:"create_time"`
}

func NewDriver() *Driver {
	return &Driver{}
}

func (p *Driver) InitDefault() {
}

func (p *Driver) GetId() (v int64) {
	return p.Id
}

func (p *Driver) GetDriverNo() (v string) {
	return p.DriverNo
}

func (p *Driver) GetName() (v string) {
	return p.Name
}

func (p *Driver) GetPhone() (v string) {
	return p.Phone
}

func (p *Driver) GetLicensePlate() (v string) {
	return p.LicensePlate
}

func (p *Driver) GetCarModel() (v string) {
	return p.CarModel
}

func (p *Driver) GetRating() (v float64) {
	return p.Rating
}

func (p *Driver) GetTotalOrders() (v int32) {
	return p.TotalOrders
}

func (p *Driver) GetTodayIncome() (v float64) {
	return p.TodayIncome
}

func (p *Driver) GetServiceScore() (v int32) {
	return p.ServiceScore
}

func (p *Driver) GetAuditStatus() (v int32) {
	return p.AuditStatus
}

func (p *Driver) GetOnlineStatus() (v int32) {
	return p.OnlineStatus
}

func (p *Driver) GetCreateTime() (v string) {
	return p.CreateTime
}
func (p *Driver) SetId(val int64) {
	p.Id = val
}
func (p *Driver) SetDriverNo(val string) {
	p.DriverNo = val
}
func (p *Driver) SetName(val string) {
	p.Name = val
}
func (p *Driver) SetPhone(val string) {
	p.Phone = val
}
func (p *Driver) SetLicensePlate(val string) {
	p.LicensePlate = val
}
func (p *Driver) SetCarModel(val string) {
	p.CarModel = val
}
func (p *Driver) SetRating(val float64) {
	p.Rating = val
}
func (p *Driver) SetTotalOrders(val int32) {
	p.TotalOrders = val
}
func (p *Driver) SetTodayIncome(val float64) {
	p.TodayIncome = val
}
func (p *Driver) SetServiceScore(val int32) {
	p.ServiceScore = val
}
func (p *Driver) SetAuditStatus(val int32) {
	p.AuditStatus = val
}
func (p *Driver) SetOnlineStatus(val int32) {
	p.OnlineStatus = val
}
func (p *Driver) SetCreateTime(val string) {
	p.CreateTime = val
}

func (p *Driver) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Driver(%+v)", *p)
}

var fieldIDToName_Driver = map[int16]string{
	1:  "id",
	2:  "driver_no",
	3:  "name",
	4:  "phone",
	5:  "license_plate",
	6:  "car_model",
	7:  "rating",
	8:  "total_orders",
	9:  "today_income",
	10: "service_score",
	11: "audit_status",
	12: "online_status",
	13: "create_time",
}

type ListDriverReq struct {
	Name     string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Phone    string `thrift:"phone,2" frugal:"2,default,string" json:"phone"`
	Status   int32  `thrift:"status,3" frugal:"3,default,i32" json:"status"`
	Page     int32  `thrift:"page,4" frugal:"4,default,i32" json:"page"`
	PageSize int32  `thrift:"page_size,5" frugal:"5,default,i32" json:"page_size"`
}

func NewListDriverReq() *ListDriverReq {
	return &ListDriverReq{}
}

func (p *ListDriverReq) InitDefault() {
}

func (p *ListDriverReq) GetName() (v string) {
	return p.Name
}

func (p *ListDriverReq) GetPhone() (v string) {
	return p.Phone
}

func (p *ListDriverReq) GetStatus() (v int32) {
	return p.Status
}

func (p *ListDriverReq) GetPage() (v int32) {
	return p.Page
}

func (p *ListDriverReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *ListDriverReq) SetName(val string) {
	p.Name = val
}
func (p *ListDriverReq) SetPhone(val string) {
	p.Phone = val
}
func (p *ListDriverReq) SetStatus(val int32) {
	p.Status = val
}
func (p *ListDriverReq) SetPage(val int32) {
	p.Page = val
}
func (p *ListDriverReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *ListDriverReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListDriverReq(%+v)", *p)
}

var fieldIDToName_ListDriverReq = map[int16]string{
	1: "name",
	2: "phone",
	3: "status",
	4: "page",
	5: "page_size",
}

type ListDriverResp struct {
	Drivers  []*Driver      `thrift:"drivers,1" frugal:"1,default,list<Driver>" json:"drivers"`
	Total    int64          `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewListDriverResp() *ListDriverResp {
	return &ListDriverResp{}
}

func (p *ListDriverResp) InitDefault() {
}

func (p *ListDriverResp) GetDrivers() (v []*Driver) {
	return p.Drivers
}

func (p *ListDriverResp) GetTotal() (v int64) {
	return p.Total
}

var ListDriverResp_BaseResp_DEFAULT *base.BaseResp

func (p *ListDriverResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListDriverResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListDriverResp) SetDrivers(val []*Driver) {
	p.Drivers = val
}
func (p *ListDriverResp) SetTotal(val int64) {
	p.Total = val
}
func (p *ListDriverResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListDriverResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListDriverResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListDriverResp(%+v)", *p)
}

var fieldIDToName_ListDriverResp = map[int16]string{
	1:   "drivers",
	2:   "total",
	255: "baseResp",
}

type GetDriverReq struct {
	DriverId int64 `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
}

func NewGetDriverReq() *GetDriverReq {
	return &GetDriverReq{}
}

func (p *GetDriverReq) InitDefault() {
}

func (p *GetDriverReq) GetDriverId() (v int64) {
	return p.DriverId
}
func (p *GetDriverReq) SetDriverId(val int64) {
	p.DriverId = val
}

func (p *GetDriverReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDriverReq(%+v)", *p)
}

var fieldIDToName_GetDriverReq = map[int16]string{
	1: "driver_id",
}

type GetDriverResp struct {
	Driver   *Driver        `thrift:"driver,1" frugal:"1,default,Driver" json:"driver"`
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewGetDriverResp() *GetDriverResp {
	return &GetDriverResp{}
}

func (p *GetDriverResp) InitDefault() {
}

var GetDriverResp_Driver_DEFAULT *Driver

func (p *GetDriverResp) GetDriver() (v *Driver) {
	if !p.IsSetDriver() {
		return GetDriverResp_Driver_DEFAULT
	}
	return p.Driver
}

var GetDriverResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetDriverResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetDriverResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetDriverResp) SetDriver(val *Driver) {
	p.Driver = val
}
func (p *GetDriverResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetDriverResp) IsSetDriver() bool {
	return p.Driver != nil
}

func (p *GetDriverResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetDriverResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDriverResp(%+v)", *p)
}

var fieldIDToName_GetDriverResp = map[int16]string{
	1:   "driver",
	255: "baseResp",
}

type UpdateDriverStatusReq struct {
	DriverId     int64 `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
	OnlineStatus int32 `thrift:"online_status,2" frugal:"2,default,i32" json:"online_status"`
}

func NewUpdateDriverStatusReq() *UpdateDriverStatusReq {
	return &UpdateDriverStatusReq{}
}

func (p *UpdateDriverStatusReq) InitDefault() {
}

func (p *UpdateDriverStatusReq) GetDriverId() (v int64) {
	return p.DriverId
}

func (p *UpdateDriverStatusReq) GetOnlineStatus() (v int32) {
	return p.OnlineStatus
}
func (p *UpdateDriverStatusReq) SetDriverId(val int64) {
	p.DriverId = val
}
func (p *UpdateDriverStatusReq) SetOnlineStatus(val int32) {
	p.OnlineStatus = val
}

func (p *UpdateDriverStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDriverStatusReq(%+v)", *p)
}

var fieldIDToName_UpdateDriverStatusReq = map[int16]string{
	1: "driver_id",
	2: "online_status",
}

type UpdateDriverStatusResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewUpdateDriverStatusResp() *UpdateDriverStatusResp {
	return &UpdateDriverStatusResp{}
}

func (p *UpdateDriverStatusResp) InitDefault() {
}

var UpdateDriverStatusResp_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateDriverStatusResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateDriverStatusResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateDriverStatusResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateDriverStatusResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateDriverStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDriverStatusResp(%+v)", *p)
}

var fieldIDToName_UpdateDriverStatusResp = map[int16]string{
	255: "baseResp",
}

type DriverService interface {
	ListDriver(ctx context.Context, req *ListDriverReq) (r *ListDriverResp, err error)

	GetDriver(ctx context.Context, req *GetDriverReq) (r *GetDriverResp, err error)

	UpdateDriverStatus(ctx context.Context, req *UpdateDriverStatusReq) (r *UpdateDriverStatusResp, err error)
}

type DriverServiceListDriverArgs struct {
	Req *ListDriverReq `thrift:"req,1" frugal:"1,default,ListDriverReq" json:"req"`
}

func NewDriverServiceListDriverArgs() *DriverServiceListDriverArgs {
	return &DriverServiceListDriverArgs{}
}

func (p *DriverServiceListDriverArgs) InitDefault() {
}

var DriverServiceListDriverArgs_Req_DEFAULT *ListDriverReq

func (p *DriverServiceListDriverArgs) GetReq() (v *ListDriverReq) {
	if !p.IsSetReq() {
		return DriverServiceListDriverArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceListDriverArgs) SetReq(val *ListDriverReq) {
	p.Req = val
}

func (p *DriverServiceListDriverArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceListDriverArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceListDriverArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceListDriverArgs = map[int16]string{
	1: "req",
}

type DriverServiceListDriverResult struct {
	Success *ListDriverResp `thrift:"success,0,optional" frugal:"0,optional,ListDriverResp" json:"success,omitempty"`
}

func NewDriverServiceListDriverResult() *DriverServiceListDriverResult {
	return &DriverServiceListDriverResult{}
}

func (p *DriverServiceListDriverResult) InitDefault() {
}

var DriverServiceListDriverResult_Success_DEFAULT *ListDriverResp

func (p *DriverServiceListDriverResult) GetSuccess() (v *ListDriverResp) {
	if !p.IsSetSuccess() {
		return DriverServiceListDriverResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceListDriverResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListDriverResp)
}

func (p *DriverServiceListDriverResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceListDriverResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceListDriverResult(%+v)", *p)
}

var fieldIDToName_DriverServiceListDriverResult = map[int16]string{
	0: "success",
}

type DriverServiceGetDriverArgs struct {
	Req *GetDriverReq `thrift:"req,1" frugal:"1,default,GetDriverReq" json:"req"`
}

func NewDriverServiceGetDriverArgs() *DriverServiceGetDriverArgs {
	return &DriverServiceGetDriverArgs{}
}

func (p *DriverServiceGetDriverArgs) InitDefault() {
}

var DriverServiceGetDriverArgs_Req_DEFAULT *GetDriverReq

func (p *DriverServiceGetDriverArgs) GetReq() (v *GetDriverReq) {
	if !p.IsSetReq() {
		return DriverServiceGetDriverArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceGetDriverArgs) SetReq(val *GetDriverReq) {
	p.Req = val
}

func (p *DriverServiceGetDriverArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceGetDriverArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceGetDriverArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceGetDriverArgs = map[int16]string{
	1: "req",
}

type DriverServiceGetDriverResult struct {
	Success *GetDriverResp `thrift:"success,0,optional" frugal:"0,optional,GetDriverResp" json:"success,omitempty"`
}

func NewDriverServiceGetDriverResult() *DriverServiceGetDriverResult {
	return &DriverServiceGetDriverResult{}
}

func (p *DriverServiceGetDriverResult) InitDefault() {
}

var DriverServiceGetDriverResult_Success_DEFAULT *GetDriverResp

func (p *DriverServiceGetDriverResult) GetSuccess() (v *GetDriverResp) {
	if !p.IsSetSuccess() {
		return DriverServiceGetDriverResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceGetDriverResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetDriverResp)
}

func (p *DriverServiceGetDriverResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceGetDriverResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceGetDriverResult(%+v)", *p)
}

var fieldIDToName_DriverServiceGetDriverResult = map[int16]string{
	0: "success",
}

type DriverServiceUpdateDriverStatusArgs struct {
	Req *UpdateDriverStatusReq `thrift:"req,1" frugal:"1,default,UpdateDriverStatusReq" json:"req"`
}

func NewDriverServiceUpdateDriverStatusArgs() *DriverServiceUpdateDriverStatusArgs {
	return &DriverServiceUpdateDriverStatusArgs{}
}

func (p *DriverServiceUpdateDriverStatusArgs) InitDefault() {
}

var DriverServiceUpdateDriverStatusArgs_Req_DEFAULT *UpdateDriverStatusReq

func (p *DriverServiceUpdateDriverStatusArgs) GetReq() (v *UpdateDriverStatusReq) {
	if !p.IsSetReq() {
		return DriverServiceUpdateDriverStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceUpdateDriverStatusArgs) SetReq(val *UpdateDriverStatusReq) {
	p.Req = val
}

func (p *DriverServiceUpdateDriverStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceUpdateDriverStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceUpdateDriverStatusArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceUpdateDriverStatusArgs = map[int16]string{
	1: "req",
}

type DriverServiceUpdateDriverStatusResult struct {
	Success *UpdateDriverStatusResp `thrift:"success,0,optional" frugal:"0,optional,UpdateDriverStatusResp" json:"success,omitempty"`
}

func NewDriverServiceUpdateDriverStatusResult() *DriverServiceUpdateDriverStatusResult {
	return &DriverServiceUpdateDriverStatusResult{}
}

func (p *DriverServiceUpdateDriverStatusResult) InitDefault() {
}

var DriverServiceUpdateDriverStatusResult_Success_DEFAULT *UpdateDriverStatusResp

func (p *DriverServiceUpdateDriverStatusResult) GetSuccess() (v *UpdateDriverStatusResp) {
	if !p.IsSetSuccess() {
		return DriverServiceUpdateDriverStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceUpdateDriverStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateDriverStatusResp)
}

func (p *DriverServiceUpdateDriverStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceUpdateDriverStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceUpdateDriverStatusResult(%+v)", *p)
}

var fieldIDToName_DriverServiceUpdateDriverStatusResult = map[int16]string{
	0: "success",
}
